### ISSUE TITLE
"cygpath: command not found" when commiting to branch

### ISSUE THREAD

**Issue by zedd3v** [desktop/desktop#10326]
"cygpath: command not found" when commiting to branch

Github desktop version: 2.5.3
OS: Windows 10

Full error:

Commit failed - exit code 1 received, with output: '/c/Users/karlo/AppData/Roaming/npm/yarn: line 5: cygpath: command not found
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'C:\Users\karlo\AppData\Local\GitHubDesktop\app-2.5.3\resources\app\git\node_modules\yarn\bin\yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}'

**Comment by tierninho** [comment]
@zedd3v Thanks for the report. This looks like an error with your shell or path settings. Can you list your reproductions steps? What shell are you using in Desktop -- see the Options settings? And share your logs from that day? See the Help menu in Desktop for the logs.

The `cygpath` program is part of the Git for Windows installation. Please ensure that you have git installed from https://git-scm.com/download/win. In general you should be using the system installed Git (i.e. Git for Windows).

**Comment by tierninho** [comment]
@zedd3v  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by donna-marijne** [comment]
I believe that the problem is due to the following code from yarn's bootstrap script on Windows:

```sh
case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac
```

So if yarn is run as part of a git hook, this will be executed in Desktop's own bundled MINGW environment, which (unlike the one bundled with Git for Windows) does not include the `cygpath` utility.

**Comment by owenashurst** [comment]
> I believe that the problem is due to the following code from yarn's bootstrap script on Windows:
> 
> ```shell
> case `uname` in
>     *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
> esac
> ```
> 
> So if yarn is run as part of a git hook, this will be executed in Desktop's own bundled MINGW environment, which (unlike the one bundled with Git for Windows) does not include the `cygpath` utility.

Is there a way to force github desktop to use the Git for Windows version instead?

**Comment by rletsin** [comment]
@tierninho 
I have the same issue.
I am using GitHub Desktop with few repositories, but issue appears only on front-end monorepo. We are using husky and yarnhook inside it, so I suppose these may cause this error. Happens on every checkout, push, merge etc. and it's pretty annoying. 
We use pnpm to manage our monorepo and this husky config inside package.json:
`"husky": {  
    "hooks": {  
      "pre-push": "pnpm run prepush", 
      "post-checkout": "yarnhook", 
      "post-merge": "yarnhook", 
      "post-rewrite": "yarnhook"
    }
  }`

OS: Windows 10
GitHub Desktop: version up to 2.6.0
git for Windows: 2.29.2
Using git bash shell
Node: 10.23.0
npm: 6.14.8
pnpm: 5.12.0

**Comment by RyanGuild-TF** [comment]
I also have been having this issue in a number of repositories. Love github desktop for visualizing commits but I have never been able to commit through the GUI.

npm global installs are in my PATH. i.e. yarn can be run in bash

very same error 

> Commit failed - exit code 1 received, with output: '/c/Users/ryan.guild/AppData/Roaming/npm/yarn: line 5: cygpath: command not found
> internal/modules/cjs/loader.js:1032
>   throw err;
>   ^
> 
> Error: Cannot find module 'C:\Users\ryan.guild\AppData\Local\GitHubDesktop\app-2.6.0\resources\app\git\node_modules\yarn\bin\yarn.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:898:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }'

OS: Windows 10
GitHub Desktop: version up to 2.6.0
git version: 2.27.0.windows.1
Using git bash shell
Node: >=14
npm: 6.14.9
pnpm: ??? - never heard of this

**Comment by Druegor** [comment]
@RyanGuild-TF I was actually able to make this work by manually copying the .../AppData/Roaming/npm/node_modules into the ...AppData\Local\GitHubDesktop\app-2.6.0\resources\app\git\ folder.  Wish I could figure out a better way to make it work but that is what I had to resort to.

**Comment by JMaio** [comment]
I'm having the same issue with GitHub Desktop, and can confirm @donna-marijne's reply that the issue seems to be with the yarn bootstrap script:

> ```shell
> case `uname` in
>     *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
> esac
> ```
This is only happening in GitHub Desktop's bundled MINGW (but **not** system Git Bash), and according to @steveward, GitHub Desktop [_ships with an internal version of Git_](https://github.com/desktop/desktop/issues/10999#issuecomment-724246553) which, again, seems to not include the `cygpath` utility.

Removing this `case` from the script lets the configured hooks run correctly in GitHub Desktop without affecting other terminals (probably). 
Looks like either GitHub Desktop's MINGW should include `cygpath`, or maybe yarn should not rely on this command...

My config:
| | |
| - | - |
| OS  | Windows 10, 20H2 (build 19042.685)  |
| GitHub Desktop | 2.6.1 |
| Git for Windows | 2.29.2.windows.3 |
| node | v15.5.0 |
| npm | 7.3.0 |
| yarn | 1.22.10 (global) / 2.4.0 (project) |
| husky | v4.3.6 |

(using yarn 2 with PnP)

**Comment by mwittmann** [comment]
I had this issue using `pnpm`  as the package manager in one of my git repos. I added `C:\Program Files\Git\usr\bin` which contains `cygpath.exe` to my `PATH` environment variable, and that resolved the issue.

**Comment by meena-erian** [comment]
I had the same problem and it turns out it was because of a pre-commit script.  

In case you're having the same problem, you can either commit from the command line while skipping the pre-commit script 
`git commit -m "fixed something" --no-verify`

or if you don't need the pre-commit script, you can delete the file `YourRepository/.git/hooks/pre-commit`

**Comment by leopucci** [comment]
> I had this issue using `pnpm` as the package manager in one of my git repos. I added `C:\Program Files\Git\usr\bin` which contains `cygpath.exe` to my `PATH` environment variable, and that resolved the issue.

This caused me another problem 

`0 [main] cygpath (6136) C:\Program Files\Git\usr\bin\cygpath.exe: *** fatal error - cygheap base mismatch detected - 0x18034C408/0x180347408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
internal/modules/cjs/loader.js:892
  throw err;
  ^`

**Comment by leopucci** [comment]
> @RyanGuild-TF I was actually able to make this work by manually copying the .../AppData/Roaming/npm/node_modules into the ...AppData\Local\GitHubDesktop\app-2.6.0\resources\app\git\ folder. Wish I could figure out a better way to make it work but that is what I had to resort to.

This workaround solved for me. Now the pre-commit hook can run yarn

**Comment by donna-marijne** [comment]
For what it's worth, my current workaround for this is to remove `yarn` and similar bootstrap scripts from git hooks and use `node` to execute the scripts directly, e.g.
```
node ./node_modules/@nrwl/cli/bin/nx.js ...
```

**Comment by wr-bezborodko-daria** [comment]
The issue still reproduces. Version 2.9.4 (x64)

**Comment by DoctorDerek** [comment]
> I had this issue using `pnpm` as the package manager in one of my git repos. I added `C:\Program Files\Git\usr\bin` which contains `cygpath.exe` to my `PATH` environment variable, and that resolved the issue.

This worked for me with yarn and cygpath.

**Comment by dennis-gonzales** [comment]
> had this issue using `pnpm` as the package manager in one of my git repos. I added `C:\Program Files\Git\usr\bin` which contains `cygpath.exe` to my `PATH` environment variable

This worked for me too, using yarn.

**Comment by dream-topdev** [comment]
> > had this issue using `pnpm` as the package manager in one of my git repos. I added `C:\Program Files\Git\usr\bin` which contains `cygpath.exe` to my `PATH` environment variable
> 
> This worked for me too, using yarn.

This worked for me too. Thanks.

**Comment by frostshoxx** [comment]
> > > had this issue using `pnpm` as the package manager in one of my git repos. I added `C:\Program Files\Git\usr\bin` which contains `cygpath.exe` to my `PATH` environment variable
> > 
> > 
> > This worked for me too, using yarn.
> 
> This worked for me too. Thanks.

This works for me as well (I had problem with VS2022 husky hooks when commit via GUI, works fine on VS Code terminal). It would be nice to have more "automated" solution, but this will do for the time being.

Thanks for the insight!

**Comment by usmangurowa** [comment]
> 

This works 100%.

**Comment by Geerodge** [comment]
> 

This works, thank you. Remember to restart Git Desktop after adding to path environment variable.

**Comment by octopushugger** [comment]
Still having this issue on 3.1.2. Really didn't wanna add C:\Program Files\Git\usr\bin to path but that was the only method that fixed it for me.

**Comment by viniciusdalastra** [comment]
I fixed moving the cygpath.exe to "%AppData%\Local\GitHubDesktop\app-3.1.3\resources\app\git\usr\bin"

This error occurred when i updated the version.

**Comment by juancolchete** [comment]
> I had this issue using `pnpm` as the package manager in one of my git repos. I added `C:\Program Files\Git\usr\bin` which contains `cygpath.exe` to my `PATH` environment variable, and that resolved the issue.

Worked for me also

**Comment by rettoua** [comment]
Even though the issue is marked as closed the problem is still there. Copying node_module folder helped to solve the problem.

**Comment by mason369** [comment]
The issue still reproduces. Version 3.2.0 (x64)

**Comment by SalmanTahir7** [comment]
Reopen this issue, it still persists no matter the update, I have to apply the same fix every time I try to commit something

**Comment by lunarmint** [comment]
> I had this issue using `pnpm` as the package manager in one of my git repos. I added `C:\Program Files\Git\usr\bin` which contains `cygpath.exe` to my `PATH` environment variable, and that resolved the issue.

Clean solution and worked for me, thanks!

**Comment by dennis-gonzales** [comment]
> Reopen this issue, it still persists no matter the update, I have to apply the same fix every time I try to commit something

I agree, the accepted solution indeed works but at the end of the day it is just a workaround and not a permanent fix.

**Comment by pisolofin** [comment]
> I had this issue using `pnpm` as the package manager in one of my git repos. I added `C:\Program Files\Git\usr\bin` which contains `cygpath.exe` to my `PATH` environment variable, and that resolved the issue.

That resolve my issue in GitKraken, thanks :)

**Comment by larsdouweschuitema** [comment]
Add the following line to the `.bashrc` or `.bash_profile` file, replacing `"C:/Program Files/Git/bin"` with the actual path to your Git "bin" folder:
```bash
export PATH=$PATH:"C:/Program Files/Git/bin"
```

`.bashr` or `. bash_profile` can be located in your user folder `"C:/Users/[name]"`.

Make sure to reload your application. Whether that is Github Desktop, SourceTree, GitKraken or anything else.

**Comment by sathish099** [comment]
> I had this issue using `pnpm` as the package manager in one of my git repos. I added `C:\Program Files\Git\usr\bin` which contains `cygpath.exe` to my `PATH` environment variable, and that resolved the issue.

Yes it is working. but it takes more time a single line of code! why? @meena-erian

**Comment by DanielYamini** [comment]
Unsubscribe

**Comment by gbarros1994** [comment]
In my case, what resolved was changing the node version

**Comment by C0rn3j** [comment]
Apparently I installed the *WRONG* git by using `chocolatey -y git`.

`winget install --id Git.Git -e --source winget` resolved it.
