### ISSUE TITLE
Race condition for switching branches and restoring stashed changes

### ISSUE THREAD

**Issue by IanBrownDelsys** [desktop/desktop#10651]
### Describe the bug

If you switch branches in the Github Desktop App for Windows, there is an inherent race condition in which you can accidentally pull the stash from one branch to another. 

### Version & OS

Windows 10: GitHub Desktop v2.5.5

### Steps to reproduce the behavior

Have multiple branches for a project
Have stashed changes in branch A
Have the stashed changes menu open so you could theoretically click "Restore or Discard"

1. Switch branches
2. Quickly click restore right after switching branches

**Comment by IanBrownDelsys** [comment]
I would just disable the stashed changes menu quicker so it can't happen

**Comment by tierninho** [comment]
@IanBrownDelsys Thanks for the report. Labelling this a bug for now. 

I couldn't reproduce that, but I noticed that after clicking `restore` and then switching branches quickly, the stash was never restored. 

Any chance you made a video?

**Comment by IanBrownDelsys** [comment]
So actually moving over my changes is really difficult, It seems to be entirely timing based. What is MORE likely is that I loose all my stashed changes alltogether. The easiest way to reproduce this is to NOT have the "Stashed changes menu" open and right after you switch branches QUICKLY click the "Stashed Changes" snackbar above the Commit area and then sniping the restore button.

Let me know if you still need a video. I've only gotten the moved changes to occur once but I can consistently loose all progress if I'm quick enough... which is really disappointing

**Comment by tierninho** [comment]
Thanks for the added notes. Having trouble getting the timing down, but due to the destructive nature of this action it should be fixed. I should eventually be be able to reproduce it.

**Comment by IanBrownDelsys** [comment]
Thanks for the follow-up. Again, let me know if you need that video and I can give it the ol' steps recorder.

**Comment by IanBrownDelsys** [comment]
Problem still persists, I was just able to move files across branches using the originally described method of sniping the restore button after a branch switch. This is in 2.5.6
