### ISSUE TITLE
Organization Repo is not showing in GitHub-Desktop (Ubuntu)

### ISSUE THREAD

**Issue by exengineer1** [desktop/desktop#13226]
No Organization repository is showing in github dekstop when using ubuntu OS

### Version & OS
Github Desktop version: 2.6.3-linux1
OS: 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

### Steps to reproduce the behavior

1. Open github dekstop
2.  From file click on **Clone Repository**
3. Under **github.com** tab you can see all of your repository
4. Search for your organization's any repo
So here is no repository from your organization you can only see your personal repo.

**Comment by tidy-dev** [comment]
@e-adware issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.

Sorry!

**Comment by kailashzversal** [comment]
Try the below things, it's work for me. 

Go to the Organisation setting --> Third-party access 
Then grant access to the "The GitHub Desktop Development App"

![Github-Desktop-(Ubuntu)](https://user-images.githubusercontent.com/77328916/144801182-256eb576-5e78-47d3-bebc-46f927b77ece.png)

**Comment by bherbruck** [comment]
@kailashzversal how did you force GitHub Desktop to _request_ access?
It is not in my org's third-party list.

**Comment by kailashzversal** [comment]
@bherbruck if it not showing in your org's third-party list then, you need to go to your Account Setting -->Integrations -->Applications -->Authorized OAuth Apps --> Click on "The GitHub Desktop Development App" --> Under Organization access sent a request to your Org's.

**Comment by andreamattioli** [comment]
In my case there are 3 accounts: my user account, organization account and organization owner (user) account.
Solution was:
- logout with my personal account from Github Desktop and from github.com
- login with organization owner account in github.com
- login in Github Desktop which uses session of organization owner 
- settings > organizations > select yours > settings > third party application > grant access 
- now all repositories are visible in Github Desktop, buy you're using wrong account
- logout from github.comand login with my personal account 
- change user in Github Desktop and now i can use my personal account with all repos

**Comment by eseidel** [comment]
This was working until recently from Windows (my GitHub Desktop could push correctly to the two organizations my account owns, no problem).

When I try to follow the instructions above, the organization oauth page, e.g. https://github.com/organizations/shorebirdtech/settings/oauth_application_policy directs me to look at my personal account:
"No pending requests
As members request access for specific applications, those requests will be listed here for your approval. You can start by browsing [your own authorized applications](https://github.com/settings/applications#authorized)."

Once I navigate to https://github.com/settings/applications#authorized, I see GitHub Desktop (from the context of my personal account), but then there is no way from there to cause GitHub desktop to request access to my two organizations.  I have not yet tried logging out/logging in to GitHub Desktop, maybe that will help.

**Comment by ryonwhyte** [comment]
Thank you for the solution @kailashzversal . Saved me a lot of time trying to figure this out

**Comment by j05hau** [comment]
> This was working until recently from Windows (my GitHub Desktop could push correctly to the two organizations my account owns, no problem).
> 
> When I try to follow the instructions above, the organization oauth page, e.g. https://github.com/organizations/shorebirdtech/settings/oauth_application_policy directs me to look at my personal account: "No pending requests As members request access for specific applications, those requests will be listed here for your approval. You can start by browsing [your own authorized applications](https://github.com/settings/applications#authorized)."
> 
> Once I navigate to https://github.com/settings/applications#authorized, I see GitHub Desktop (from the context of my personal account), but then there is no way from there to cause GitHub desktop to request access to my two organizations. I have not yet tried logging out/logging in to GitHub Desktop, maybe that will help.

Navigate to [here](https://github.com/settings/applications#authorized) and revoke access to GitHub Desktop Development App, sign out of the GitHub Desktop Ubuntu app, then sign back in and grant it access again - you will see that there's a list of orgs you can grant access to when requesting permissions

**Comment by KiribalanS** [comment]
> > This was working until recently from Windows (my GitHub Desktop could push correctly to the two organizations my account owns, no problem).
> > When I try to follow the instructions above, the organization oauth page, e.g. https://github.com/organizations/shorebirdtech/settings/oauth_application_policy directs me to look at my personal account: "No pending requests As members request access for specific applications, those requests will be listed here for your approval. You can start by browsing [your own authorized applications](https://github.com/settings/applications#authorized)."
> > Once I navigate to https://github.com/settings/applications#authorized, I see GitHub Desktop (from the context of my personal account), but then there is no way from there to cause GitHub desktop to request access to my two organizations. I have not yet tried logging out/logging in to GitHub Desktop, maybe that will help.
> 
> Navigate to [here](https://github.com/settings/applications#authorized) and revoke access to GitHub Desktop Development App, sign out of the GitHub Desktop Ubuntu app, then sign back in and grant it access again - you will see that there's a list of orgs you can grant access to when requesting permissions

thank you for your solution. it really helped a lot.

**Comment by Andrew-Pynch** [comment]
> 

its 2023 can we get this already :laughing:

**Comment by KnightChaser** [comment]
> Try the below things, it's work for me.
> 
> Go to the Organisation setting --> Third-party access Then grant access to the "The GitHub Desktop Development App"
> 
> ![Github-Desktop-(Ubuntu)](https://user-images.githubusercontent.com/77328916/144801182-256eb576-5e78-47d3-bebc-46f927b77ece.png)

Thanks for your reply, it actually worked :)

**Comment by Arrnav** [comment]
Done all the above steps, signed out and back into github desktop after revoking existing OAuth permission, authorized organization access when asked, then finally went to check Third-party application access policy under organization settings again, but GitHub desktop does never appears in that list.

**Comment by miigotu** [comment]
I had to sign out/revoke github desktop under my user account on github (not in the org), and then sign back in with github desktop. When the popup to all/deny shows up, make sure your organization shows a green check (or click authorize) before clicking allow.

For some reason it was allowed on my personal profile, and did not show on the organization and I couldnt see any organizations in github desktop, and when I forced a re-login they all were green checks, but now I can see them in github desktop. Probably because my authorization was from a long time ago with a beta version of github desktop and that was on linux. Now on windows.

**Comment by Amsoht** [comment]
Still have this issue but on github desktop for ubuntu (shiftkey repository): https://github.com/shiftkey/desktop/issues/948
I am leaving this here, in case someone stumbles across this.
I Tried all variations of logging in and out again on ubuntu github desktop mentioned above. On the personal accounts, the app was listed with a green checkmark to its side. However in the organization third party app list, it does not show up. 
![grafik](https://github.com/desktop/desktop/assets/57802852/bf1b7486-d1a2-444c-a185-369c026b8e62)

No idea why it does work with e.g. zenodo on the other hand. I had to remove restrictions for the organization to get github desktop to work... No idea why it does work with e.g. zenodo on the other hand.

![grafik](https://github.com/desktop/desktop/assets/57802852/a2c927d0-1522-4ca1-a5cb-07334781fee6)

**Comment by itseniorscris** [comment]
> [@e-adware](https://github.com/e-adware) issues related to the unofficial Linux fork of GitHub Desktop can be filed here:
> 
> https://github.com/shiftkey/desktop/issues
> 
> At this time we only officially provide support for macOS and Windows.
> 
> Sorry!

Useless

**Comment by AlEkramHossainAbir** [comment]
> [@e-adware](https://github.com/e-adware) issues related to the unofficial Linux fork of GitHub Desktop can be filed here:
> 
> https://github.com/shiftkey/desktop/issues
> 
> At this time we only officially provide support for macOS and Windows.
> 
> Sorry!

still no support for Linux?
