### ISSUE TITLE
On maximized window unable to show windows 11 taskbar when set to auto hide

### ISSUE THREAD

**Issue by Maxd63** [desktop/desktop#14009]
### Github desktop is obstructing windows trigger for the auto hide taskbar

<img src="https://i.ibb.co/BcHcfvM/image-2022-02-24-180654.png"/> 

Mouse is in resize mode instead of showing the taskbar.

### Version
Version 2.9.10 (x64)
Windows 11 10.0.22000 Build 22000

**Comment by steveward** [comment]
Thanks for the report @Maxd63. I tested this out on my Windows 11 machine and was unable to reproduce the issue in fullscreen mode in GitHub Desktop -- the taskbar reappeared correctly when set to auto-hide. Is there anything else I could be missing when attempting to reproduce this?

**Comment by steveward** [comment]
This was also reported in #14017 in a multi-monitor setup. @Maxd63 are you using multiple monitors with your Windows machine?

**Comment by steveward** [comment]
Related Electron issue: https://github.com/electron/electron/issues/32957

**Comment by mihaibrana** [comment]
Using Windows 10 here. Github Desktop prevents taskbar from showing IF:
  1. is maximized
  2. is NOT maximized but has maximized dimensions (i.e. covers the entire screen).

I have uploaded a video that shows the bug in all its beauty :).

https://www.youtube.com/watch?v=_qHPS2gOwEw

**Comment by BlakeRBM** [comment]
I am also currently having what appears to be this issue (win10, tried reinstalling the app). However, restarting the windows explorer task from task manager appears to temporarily fix it, at least until you re-fullscreen the app.

To see this:
 1. Open Github Desktop, and fullscreen the application. At this point, when attempting to access an auto-hide taskbar, the resizing cursor icon should instead display due to the bug.
 2. Open task manager and scroll down to the bottom. Click the Windows Explorer task (responsible for handling the windows, desktop, taskbar, etc), and restart it.
 3. After focusing the Github Desktop application, the taskbar should now appear when the cursor is moved to the bottom of the screen. You can switch to other applications, and come back to Github Desktop, and effect will remain.
 4. Un-maximise Github Desktop, then maximise it. When trying to access the taskbar, the resizing cursor will appear, and the taskbar will be inaccessible without using another method of activating the taskbar.

**Comment by samuel-lucas6** [comment]
I've also had this problem on Windows 10 for as long as I can remember since I started using auto-hide. I use two or three monitors. @BlakeRBM That fix works until I minimise GitHub Desktop.

**Comment by justingolden21** [comment]
I have this problem on Windows 10 as well. Is anyone looking into this? It's been an issue way before February. It basically means I can't check the time when Desktop is open lol.

**Comment by sergiou87** [comment]
Closing this as it will be finally fixed with the Electron upgrade to v19 in 3.0.8. See https://github.com/desktop/desktop/pull/15239

**Comment by MikaAtom** [comment]
The problem is still present today. On both stable and insider releases
