### ISSUE TITLE
Can't add repository to trust...

### ISSUE THREAD

**Issue by Scoofer4** [desktop/desktop#14403]
### The problem

I can't add my directory to trusted repository becouse button "Trust repository..." after click doesn't response. Would you help me or advice me where problem is, please? Thank you Roman

### Release version

Version 2.9.14 (x64)

### Operating system

Win 10

### Log files

2022-04-18T08:27:37.598Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 6 repositories took 1.3s of which 0.0s paused, total 1.3s
2022-04-18T08:51:09.008Z - info: [ui] [AppStore] loading 7 repositories from store
2022-04-18T08:51:09.015Z - info: [ui] [AppStore] found account: Scoofer4 (MetaverseMedia.cz)
2022-04-18T08:51:09.607Z - info: [ui] Subscribed 'Scoofer4' to Alive channel
2022-04-18T08:51:09.853Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-18T08:51:09.858Z - info: [ui] execPath: 'C:\Users\Roman Fiala\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-18T08:51:17.223Z - info: [ui] [BranchPruner] Last prune took place 11 hours ago - skipping
2022-04-18T08:51:24.775Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 6 repositories took 1.2s of which 0.0s paused, total 1.2s
2022-04-18T20:43:02.262Z - info: [ui] [AppStore] loading 7 repositories from store
2022-04-18T20:43:02.267Z - info: [ui] [AppStore] found account: Scoofer4 (MetaverseMedia.cz)
2022-04-18T20:43:02.585Z - info: [ui] [BranchPruner] Last prune took place 22 hours ago - skipping
2022-04-18T20:43:02.682Z - info: [ui] launching: 2.9.14 (Windows 10.0.19044)
2022-04-18T20:43:02.687Z - info: [ui] execPath: 'C:\Users\Roman Fiala\AppData\Local\GitHubDesktop\app-2.9.14\GitHubDesktop.exe'
2022-04-18T20:43:02.699Z - info: [ui] Subscribed 'Scoofer4' to Alive channel
2022-04-18T20:43:05.681Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.028s)
2022-04-18T20:43:35.095Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 6 repositories took 1.5s of which 0.0s paused, total 1.5s

### Screenshots

![image](https://user-images.githubusercontent.com/82614547/163875323-c088f599-d98b-4e91-8063-5ecd098eae85.png)

**Comment by tsvetilian-ty** [comment]
Hi @Scoofer4 that issue has been fixed in the latest version in the [beta channel](https://desktop.github.com/beta/). Check out this comment and issue: https://github.com/desktop/desktop/issues/14336#issuecomment-1099881641

**Comment by niik** [comment]
As @tsvetilian-ty already said, this issue is being tracked in https://github.com/desktop/desktop/issues/14336. Please subscribe to that to follow along. The [latest update](https://github.com/desktop/desktop/issues/14336#issuecomment-1099881641) as of writing this is that we've shipped an update to our [beta channel](https://desktop.github.com/beta/) which solves the issue of WSL and NAS (or path beginning with `//`) not working. We're planning on shipping an updated version to our production channel this week.

**Comment by LeRouxJonathan** [comment]
On WSL2 in Windows 11, this issue still persists, wherein clicking on the "Trust Repository" button doesn't work. The spinning icon displays on click, but then quickly disappears.

**Comment by steveward** [comment]
@LeRouxJonathan thanks for sharing that. Would you mind opening a new issue and uploading your log file so we can investigate this? Thanks.
