### ISSUE TITLE
GH Desktop stopped working after update to MacOS 13 Ventura

### ISSUE THREAD

**Issue by MarcPinnell** [desktop/desktop#15539]
### The problem

After upgrading to Ventura, GH Desktop stopped working on my M1 MacMini. No issues before with the 5-6 connected repo prior to upgrade. After launching it will go through its normal startup and while sitting there will start throwing errors after 10 seconds or so. I am assuming that the errors are being caused by GHD starting its scan of the current repo.

If you dismiss the errors and wait another 10 seconds or so, the errors will pop back up. At no point can I try to commit or publish.

I have tried removing the GHD directory from ~/Library/Application Support/ and removing GHD.app and then reinstalling with a fresh download from the website.

I have also made sure that my XCode CLI tools are up to date.

### Release version

3.1.2 (arm64)

### Operating system

MacOS 13.0 Ventura

### Steps to reproduce the behavior

1. Launch GHD
2. Wait 10 seconds after selecting a Repo (if one isn't already selected)

### Screenshots

![Screenshot 2022-10-29 at 1 13 47 PM](https://user-images.githubusercontent.com/4871176/198850848-5d88cd14-37dd-426b-873e-09e38d8c4d5a.png)
![Screenshot 2022-10-29 at 1 13 51 PM](https://user-images.githubusercontent.com/4871176/198850849-dd9c7089-5be5-4280-88d2-9ef97ccbe6e5.png)

### Additional context

Errors messages I am seeing (one right after the other):

`Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --`

`Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes`

`Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git log HEAD --date=raw --max-count=100 --skip=0 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color --`

**Comment by sergiou87** [comment]
Hi @MarcPinnell ! 👋 

Could you open a terminal in your repository folder and run any of those commands like `/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --`? I'd love to know if you get the right output or if it fails from the terminal too 🤔 

Also, could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by MarcPinnell** [comment]
Tried to run the command you sent over and got a "Bus Error". 

```
marcpinnell@Marcs-Mac-mini billing.lighthouse.local % /Applications/GitHub\ Desktop.app/Contents/Resources/app/git/bin/git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
zsh: bus error  /Applications/GitHub\ Desktop.app/Contents/Resources/app/git/bin/git log -g  
```

Logs attached.
[2022-10-29.desktop.production.log](https://github.com/desktop/desktop/files/9901877/2022-10-29.desktop.production.log)
[2022-10-31.desktop.production.log](https://github.com/desktop/desktop/files/9901879/2022-10-31.desktop.production.log)

**Comment by sergiou87** [comment]
@MarcPinnell that looks like a problem unrelated to Desktop. What I mean is it doesn't look like a bug 🤔  It's more something that I'd expect to get fixed by rebooting ~~or reinstalling the app~~ EDIT: I see you already tried reinstalling the app, sorry I forgot 😓 

Could you check if any of those fix the issue?

**Comment by MarcPinnell** [comment]
I have reinstalled the app multiple times over the past couple days. Including, at one point, switching to the beta version (I switched back after that didn't solve the issue).
I don't believe I had ever tried a restart (other than the one following the install of Ventura). So, did it just now. It didn't immediately pop up with those errors, so I was hopeful! I did a commit and it came up with:

Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git commit -F -

What's interesting is that it appears to have actually done the commit as it is now reporting "nothing to commit". I cannot push from GHD though. I fired up the Nova editor (which has GH built in) and was able to do the push from there.

While I was typing this I got a series of error messages from GHD that match the stuff in the initial report above. Attached is the current log.

[2022-10-31.desktop.production.log](https://github.com/desktop/desktop/files/9902619/2022-10-31.desktop.production.log)

**Comment by sergiou87** [comment]
Super weird! But it seems like there is wrong with your setup, I have no idea what could be 😕  Do you have anything installed that could affect how other apps work? (like an antivirus or firewall)

From your logs I see your `beacon-lighthouse` is in a different volume. Is that a network volume? Maybe that's the problem and it works fine if you have the clone locally in your machine?

Other than that, the only ideas I have to narrow down the issue are:
- Try recloning those repos or cloning a new one, to see if the issue reproduces in those.
- Try GitHub Desktop with the very same repos in a different machine (with or without macOS 13 Ventura)

**Comment by MarcPinnell** [comment]
The only difference on my machine from last week until now is the install of Ventura. Prior to Ventura, GHD worked flawlessly with these same repos (there are 4 or 5) on the networked volume.

During one of the reinstalls of GHD I deleted all the app settings as well as the app itself. I currently only have the one repo connected to GHD because of that. I just tried to add a second one (cattle) from the network volume and GHD is telling me it isn't a Repo! Yikes.

I opened up the Nova editor and opened the Cattle project, made a change and was able to commit and push it to the GitHub server. I can continue working this way if I have to, but Nova is a bit slower in committing than GHD for some reason (I think it is related to the network volume), which is why I had switched to GHD a year ago.

**Comment by sergiou87** [comment]
Then I'd assume something changed in macOS Ventura regarding network volumes 😞 I don't think there is anything GitHub Desktop can do for this as it only interfaces with `git`, running commands on your behalf to get things done 😕  Given you also saw that very same problem when running the `git` command by yourself from the terminal… I think there isn't much we can do.

The last suggestion I'd made is to try the very same `git` command but using the system's `git`: `git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --`

And see if that makes a difference, in case the `git` we bundle with Desktop is somehow broken for network drives while the system's `git` isn't 🤔

**Comment by MarcPinnell** [comment]
Thanks for working through this with me. I have no idea why Nova works, but GHD doesn't. Very odd. I think you are right in that it has to be tied to Ventura. Maybe Nova bundles their own commands and doesn't rely on the system?

I ran the command you gave me - actually I ran both the direct command and the GHD command - and got basically the same results: 

```
marcpinnell@Marcs-Mac-mini billing.lighthouse.local % git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
zsh: bus error  git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
ea0c0da4c9661facc778ca33ca928f4864624ebe (HEAD -> lh-billing, origin/lh-billing) HEAD@{0}: commit: Continuing work on customer portal

marcpinnell@Marcs-Mac-mini billing.lighthouse.local % "/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git" log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
zsh: bus error  "/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git" log -g 
ea0c0da4c9661facc778ca33ca928f4864624ebe (HEAD -> lh-billing, origin/lh-billing) HEAD@{0}: commit: Continuing work on customer portal
```

**Comment by sergiou87** [comment]
~~Looking at the output of both of those command, my bet is Nova uses~~ I just checked and Nova uses built-in git commands using [libgit2](https://github.com/libgit2/libgit2):

![2022-10-31 at 17 55](https://user-images.githubusercontent.com/1083228/199064625-47f48a9d-6679-4a71-9600-05b81bb15e5e.png)

Anyway, something I just noticed in your last comment is that those `git` commands not only show the `zsh: bus error` line, but also the output you would expect. Is that correct?

If that's correct, can we somehow ignore the `zsh: bus error` in the app and process the rest of the output? 🤔 Could you do `echo $?` after running either of those commands? If it prints something other than `0`, we definitely cannot.

Another idea I just had: if you have a custom `~/.zshrc` file, whatever you wrote there could cause issues. Try renaming that file temporarily, open a new terminal and then run those commands again.

**Comment by MarcPinnell** [comment]
Thanks for following the idea of Nova using something different. So odd that it works fine...

Tried the echo:

```
marcpinnell@Marcs-Mac-mini ~ % cd /Volumes/sites.local/billing.lighthouse.local              
marcpinnell@Marcs-Mac-mini billing.lighthouse.local % git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
zsh: bus error  git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
ea0c0da4c9661facc778ca33ca928f4864624ebe (HEAD -> lh-billing, origin/lh-billing) HEAD@{0}: commit: Continuing work on customer portal
echo $?
138
marcpinnell@Marcs-Mac-mini billing.lighthouse.local % 
```

Checked the .zshrc file and found one line: eval "$(rbenv init - zsh)"

Renamed and reran the commands (restarted terminal first), doesn't appear it helped unfortunately:

```
marcpinnell@Marcs-Mac-mini billing.lighthouse.local % git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
zsh: bus error  git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
ea0c0da4c9661facc778ca33ca928f4864624ebe (HEAD -> lh-billing, origin/lh-billing) HEAD@{0}: commit: Continuing work on customer portal
echo $?                                                       
138
marcpinnell@Marcs-Mac-mini billing.lighthouse.local % 

```

**Comment by MarcPinnell** [comment]
Also you asked about the output of the command. Not sure what you mean by "what you would expect". sorry not familiar with CLI git.

That line does show the commit/push that I was able to get completed through Nova after trying to commit with GHD, getting and error and not being able to go any further. When I opened Nova, it showed one push waiting, which I did. According to Nova the commit had completed.

**Comment by sergiou87** [comment]
Thank you! Yeah with "expected output" I meant a complete list of commits , but seems like only one commit is displayed. And the `echo $?` 138 means Desktop detected it as an error so we can't really do anything to ignore it :(

If your `.zshrc` didn't make a difference, it has to be something related to Ventura. I'm gonna leave this open marked as `needs investigation` but I don't have much faith it can be solved by us :(

Sorry I can't be of more help!

**Comment by MarcPinnell** [comment]
Appreciate you doing what you have. It's a real head scratcher!

**Comment by mattiasj** [comment]
I had the same issue but things seem to work as normal after I cloned my repo to my macs HD instead of the Google Drive virtual one

**Comment by MarcPinnell** [comment]
Interesting. Pointing more and more to Apple maybe breaking something with remote drives? Unfortunately I am not in a situation where I can move the project off the remote drive.

**Comment by ericHanson13** [comment]
I was having the same issue, running all my projects from a Google Drive.  I moved them all to my Mac then "found" the folders in Desktop and everything started working again with no errors.  Just FYI.

**Comment by MarcPinnell** [comment]
What's interesting is that I can commit/push from Nova without issue. But CLI or GH Desktop will not work with these remote volumes. Unfortunately, whatever code Nova uses is really slow (takes 2-3 minutes to commit the simplest of changes), but at least it works.

**Comment by sergiou87** [comment]
> whatever code Nova uses is really slow (takes 2-3 minutes to commit the simplest of changes)

Maybe that's because of the same reason and before macOS Ventura it was as fast as one would expect? 🤔

**Comment by MarcPinnell** [comment]
No. Nova has been very slow for some time now. Ever since I moved my development/repositories to an external SMB volume it has been slow in doing commits. I have worked with their support but not found a solution as of yet. I eventually gave up and switched to GH Desktop. Unfortunately whatever Apple appears to have done in Ventura breaks Git on external volumes and therefore GH Desktop is no longer an option. Not sure why Nova still works - at least well enough to keep working.

**Comment by daniel-maiorano** [comment]
Same behaviour for me after upgrade to Ventura, when trying to do a commit from a network volume
<img width="670" alt="image" src="https://user-images.githubusercontent.com/8591536/206441773-e9e4609e-d75a-4c18-a56c-59477c23ca79.png">

**Comment by steveward** [comment]
Two reports in #15705 and #15727. I was able to reproduce this issue as well with a network drive on macOS Ventura.

**Comment by xaveervanderlaan** [comment]
This issue is also present when mounting a share with mount_smbfs and using GIT within a IDE like PHPstorm (GIT crashing).

Please fill a feedback/bug report through [https://developer.apple.com/bug-reporting/](https://developer.apple.com/bug-reporting/) if you haven't already so this issue can get fixed quicker by Apple.

We already have a couple of similar reports.
<img width="426" alt="image" src="https://user-images.githubusercontent.com/49719447/207802248-9e975032-c09a-4098-b38e-d976decbc7e9.png">

**Comment by MarcPinnell** [comment]
Saw there is a new version of Desktop, but don't see a fix for this in the Release Notes. Any ETA?

**Comment by sergiou87** [comment]
@MarcPinnell we have some git engineers looking into this, although it looks like a problem on Apple's side. Definitely no ETA, sorry!

**Comment by fisherman159** [comment]
first boss then apple

18 Oca 2023 Çar 12:29 tarihinde Sergio Padrino ***@***.***>
şunu yazdı:

**Comment by MarcPinnell** [comment]
My only hesitation to think this is an Apple problem is that Panic's Nova code editor is still working fine (thank goodness as that is keeping me working). If it were an Apple problem, you would think it would be across the board and not just some apps that were broken.
Or am I missing something?

**Comment by fisherman159** [comment]
we both know that the problem is not apples

18 Oca 2023 Çar 17:31 tarihinde Marc Pinnell ***@***.***>
şunu yazdı:

**Comment by Phishion** [comment]
This problem also exists in sourcetree, I think it is a bug of Apple about external storage, this problem is still not fixed in macOS 13.2

**Comment by MarcPinnell** [comment]
It's been almost 4 months since this was opened. Any updates on when it will be fixed?

**Comment by sergiou87** [comment]
Nope, sorry 😞  Again, this seems something external to Desktop 😕 The difference with Nova is that [Nova seems to use libgit2 instead of invoking the git executable](https://github.com/desktop/desktop/issues/15539#issuecomment-1297394291). I think this is something either git or Apple have to fix 😕 

The git engineers I mentioned in a previous comment weren't able to reproduce the issue so we're kind of stuck… 😞

**Comment by MarcPinnell** [comment]
All. Updated my mac to Ventura 13.2.1 just now and was able to run GH Desktop without issue. I was able to load multiple repositories and even committed/pushed a change to GH. Fixed?

**Comment by MarcPinnell** [comment]
Well, shoot. Just after posting the previous message I went back into GH Desktop and the same old error was sitting there. Odd that I was able to work with it for 5ish minutes before the error popped up. Before I never got that far as the error would pop up shortly after connecting.

`Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git log origin/dev..dev --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color --`

**Comment by moe1619** [comment]
Having similar issues. Thanks for working on this!

**Comment by MarcPinnell** [comment]
Fingers crossed for Mac OS 13.3 which has a reported SMB fix....

https://www.macrumors.com/2023/03/23/macos-13-3-fixes-network-file-sharing/

**Comment by moe1619** [comment]
Thanks for the update!

**Comment by xaveervanderlaan** [comment]
Mac OS Ventura 13.3 didn't fix it for me but on the bright side the issue I have opened through Apple's feedback tool did have a comforting message.

Potential fix identified - For a future OS update.

So a little patience is still required from Apple.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/49719447/228451235-39afd850-a604-41b0-89c8-47c23ad6cc53.png">

**Comment by emquardokus** [comment]
@xaveervanderlaan it looks like Github desktop has an Apple Silicon version and this seems to work on my Apple laptop M1 chip: https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64
I was having the same issues with the previous version not working with my laptop after I upgraded to Ventura OS.

**Comment by MarcPinnell** [comment]
What version of GH Desktop are you running. I am running on an M1 with the AS version of GH Desktop and it doesn't work (per the posts above).

**Comment by opus-nbonenberger** [comment]
I am experiencing the same problem with 

GitHub Desktop 3.2.9
macOS 13.5 (22G74)
git version 2.39.2 (Apple Git-143)

when the local repository is on a SMB share (Windows Server 2022).

`Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git log HEAD --date=raw --max-count=100 --skip=0 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color --`

`Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes`

`Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --`

**Comment by xaveervanderlaan** [comment]
Any brave soul willing to test if the problem got fixed in the Mac OS Sonoma Beta?

Also as a reminder please report this problem with the Apple Developer feedback tool: https://developer.apple.com/bug-reporting/

**Comment by gabriuss** [comment]
Unfortunately Sonoma has not solved this issue.

**Comment by Phishion** [comment]
It seems that Sonoma 14.2 has fixed this bug ：）

**Comment by gabriuss** [comment]
> It seems that Sonoma 14.2 has fixed this bug ：）

Holy s@#$ they actually did! Just tested it, seems to be working just fine. I'll go read 14.2 release notes to see how they did this.

**Comment by steveward** [comment]
That's great to hear! ✨  

I'll close this issue out, but let us know if this appears again.

**Comment by kubraayazici** [comment]
I am taking this error when I want to connect started rtsp server as a client. Can you help me how it solved?
----------------------------------------------------------------------------------------------------------------------
./test-launch "( videotestsrc ! videoconvert ! timeoverlay font-desc='Sans, 120' ! tee name=t t. ! queue ! autovideosink sync=false name=source t. ! x264enc speed-preset=ultrafast tune=zerolatency ! rtph264pay name=pay0 pt=96 )"

stream ready at rtsp://127.0.0.1:8554/test
zsh: bus error  ./test-launch
