### ISSUE TITLE
Can not configure the SSH Key or Password which means I cannot push or fetch from some of my repositories

### ISSUE THREAD

**Issue by JRSofty** [desktop/desktop#15752]
### The problem

So for example I'm hosting my personal webpage code in a repository. Although through my IDE (VS Code) I can fetch, push and pull, when attempting to do this in the GitHub desktop app I get a message saying there is a problem, and when I click the button to attempt to correct the problem, which is likely changing the key or password I'm using to communicate with my repository, there is no where to configure this. So basically for this repository I cannot use this app. I have to do everything elsewhere.

### Release version

3.1.2

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Select my repository
2. Click Fetch
3. Receive error message
![image](https://user-images.githubusercontent.com/1228089/206477842-1a9ea104-fa5d-45ff-89b4-fbcb3b34fc94.png)

4. Clicking "More Options" brings me here where there are no options to correct the authentication
![image](https://user-images.githubusercontent.com/1228089/206478080-0a444b8e-8975-4d13-8d03-173d7e6d3fd9.png)

### Log files

[2022-12-08.desktop.production.log](https://github.com/desktop/desktop/files/10186530/2022-12-08.desktop.production.log)

**Comment by steveward** [comment]
@JRSofty thanks for the issue. It looks like your SSH key doesn't have the correct permissions set:

```
Permissions for 'C:\\Users\\jrsof/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "C:\\Users\\jrsof/.ssh/id_rsa": bad permissions
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Setting the key permissions to something more restrictive should resolve this. [This solution](https://superuser.com/questions/1296024/windows-ssh-permissions-for-private-key-are-too-open#:~:text=You%20locate%20the%20file%20in,control%22%20and%20save%20the%20permissions.) should work. I'm going to close this out, but let me know if you run into any issues!

**Comment by JRSofty** [comment]
Hi and thanks for that information, however that does not completely solve the problem. You see this error only occurs on some of my repositories. For example here is the log where I'm pushing a change into a different repository, the same warning messages appear yet this time I do not receive an error message. My changes are pushed to the branch as it expected. 

I can make the change to my ssh keys so that only I can access them, but I don't think that will correct the problem totally. If the key fails on one repository, I would assume that it fails on all my repositories, yet it doesn't and it's not clear as to why?
[2022-12-08.desktop.production.log](https://github.com/desktop/desktop/files/10188572/2022-12-08.desktop.production.log)


Quick edit, and after correcting my permissions it did work for the ones that weren't working. The question still hangs as to why it allowed me to push to the other repository without a problem even with the SSH settings the way they were?

**Comment by steveward** [comment]
Are you possibly using HTTPS with some repositories and SSH with others? You can check by going to `Repository` > `Repository Settings` > `Remote`.

**Comment by JRSofty** [comment]
Ah @steveward  that's got it. Thanks. I had always assumed I had everything over the SSH. Ok that's got it cleared up.
