### ISSUE TITLE
Pushes/pulls over SSH fail

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1795]
See https://github.com/desktop/desktop/issues/1738.

It turned out the difference was between using the SSH URL or the HTTPS URL. They were able to push fine over SSH using Tower. So it's not clear what's different about Desktop that made it fail.

**Comment by joshaber** [comment]
Now that we're inheriting the environment, I'm hopeful this has been fixed 🙏 We can reopen if not.

**Comment by IdanAdar** [comment]
I can confirm this works now with GitHub Enterprise.

p.s.,
User thumbnails are still broken...
