### ISSUE TITLE
With version 3.4.0, we receive error - git: 'remote-codecommit' is not a git command. It worked on Version 3.3.18.

### ISSUE THREAD

**Issue by connectpritish** [desktop/desktop#18729]
### The problem

When we try to fetch the branch from origin, it throws the below error.

2024-05-31T15:11:00.205Z - info: [ui] No submodules found. Skipping "git submodule status"
2024-05-31T15:11:04.123Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 1.197s)
2024-05-31T15:11:09.689Z - info: [ui] [Timing] Action 'checkout branch from list' for 'Test-Repository' took 0.000s
2024-05-31T15:11:11.730Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
git: 'remote-codecommit' is not a git command. See 'git --help'.

2024-05-31T15:11:36.232Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
git: 'remote-codecommit' is not a git command. See 'git --help'.

### Release version

3.4.0

### Operating system

Windows 10

### Steps to reproduce the behavior

Select a remote branch and click on "Fetch Origin".
Note that we are using git-remote-codecommit for AWS CodeCommit authentication.

### Log files

2024-05-31T15:11:00.205Z - info: [ui] No submodules found. Skipping "git submodule status"
2024-05-31T15:11:04.123Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 1.197s)
2024-05-31T15:11:09.689Z - info: [ui] [Timing] Action 'checkout branch from list' for 'Test-Repository' took 0.000s
2024-05-31T15:11:11.730Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
git: 'remote-codecommit' is not a git command. See 'git --help'.

2024-05-31T15:11:36.232Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
git: 'remote-codecommit' is not a git command. See 'git --help'.

### Screenshots

![image (6)](https://github.com/desktop/desktop/assets/171364529/890f7699-81a0-44bf-8444-c7ace125f301)

### Additional context

It worked on Version 3.3.18

**Comment by eccen-3k** [comment]
Also getting the same.
I have 2 computers that are showing the same issue in version 3.4.0.
It works before I update from version 3.3.18.

**Comment by amonigal** [comment]
I just upgraded to 3.4.0 and I am having the exact same problem. I can perform `git pull` but not `git push`.
![image](https://github.com/desktop/desktop/assets/125510641/20261500-b137-4ae2-8f52-3a57a25df3bc)

**Comment by RitaSaraiva** [comment]
I'm having the same issue and I'm also at 3.4.0, does someone know if it's possible to go back to version 3.3.18 ?
@sergiou87 I saw in the other issue that was closed that you asked for the logs and I'm attaching the logs for today (when the issue occurred)
[2024-06-04.desktop.production.log](https://github.com/user-attachments/files/15546440/2024-06-04.desktop.production.log)

**Comment by nikant20** [comment]
I am also facing exactly the same issue after upgrading to 3.4.0. How can we go back to old version?

**Comment by Nic-vdwalt** [comment]
Having the same troubles.

**Comment by Bhadja** [comment]
same trouble, cannot pull either

**Comment by tidy-dev** [comment]
👋 Sorry for the frustration. This has the same root cause as this [tracking ticket for hooks failing](https://github.com/desktop/desktop/issues/18739). You can [download 3.3.18](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktopSetup-x64.exe). It will unfortunately try to auto update. Keep an eye on that hooks tracking ticket for an update, we will try to get a fix out tomorrow.

**Comment by Krperson88** [comment]
Sent from my Metro By T-Mobile 5G LTE Android Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by amonigal** [comment]
This has been resolved in version 3.4.1 (for me)
![image](https://github.com/desktop/desktop/assets/125510641/55eafc66-1d7f-4ea0-b328-53eec25ed34c)

**Comment by connectpritish** [comment]
My team is still facing issue on 3.4.1 - Are we missing something?

**Comment by steveward** [comment]
@connectpritish can you please open a new issue and share your log file so that we can investigate further? Thanks.
