### ISSUE TITLE
There's no space preservation between "last checked" text and the interpolated date

### ISSUE THREAD

**Issue by nicksp** [desktop/desktop#20135]
### The problem

When using `display: flex` on a container, the whitespace text nodes between elements can be handled differently than in normal flow layout, i.e. they can be squeezed between other flex items, hence they can visually collapse.

### Release version

Version 3.4.17 (arm64)

### Operating system

macOS 15.3.1

### Steps to reproduce the behavior

1. About GitHub Desktop
2. Click Check for Updates
3. Observe there's no visual space between "last checked" and a date value

### Screenshots

![Image](https://github.com/user-attachments/assets/3cd5ff9b-be62-42ac-806c-935016541fcd)

![Image](https://github.com/user-attachments/assets/3c42c603-766d-4c88-bdc3-50765185b6f2)

![Image](https://github.com/user-attachments/assets/d233fae2-911f-4c68-82f7-3806b38a5d82)

**Comment by niik** [comment]
Hey @nicksp, thanks for reporting this and for the proposed fix. I believe this was addressed in https://github.com/desktop/desktop/pull/20094 but it didn't make it into the production release. Are you still able to reproduce this problem with the latest changes on development?

**Comment by nicksp** [comment]
Yes, it's still reproducible @niik. The issue is with the `message` prop, not `richMessage` as in the referenced PR. #20094 fixed a different occasion.

**Comment by niik** [comment]
@nicksp Thanks for the quick reply. I can't seem to reproduce this on development though. Got any clue as to what it is I'm missing?

<img width="337" alt="Image" src="https://github.com/user-attachments/assets/7848c1c9-40d2-46b8-bc7a-698ed8c01b07" />

<img width="645" alt="Image" src="https://github.com/user-attachments/assets/8dd3051a-cdda-4b17-a295-1e71848b5e47" />

**Comment by nicksp** [comment]
Alright, I did pull the latest changes on `development` and it indeed seems to be fixed now with the `p` wrapping around. Thanks for checking in.

**Comment by niik** [comment]
Wonderful, thanks for reporting back!
