### ISSUE TITLE
Open in Atom not working in Github Desktop

### ISSUE THREAD

**Issue by empgithub** [desktop/desktop#3123]
### Description

I have just installed Atom 1.21.1 (x64), and then Github Desktop (1.0.4) on a Win 10 Pro machine. In the desktop client I cloned a repository form Gitlab, and up to this point, everything seemed to work fine. Up to the point I wanted to open the repository in Atom. I tried the menu, right clicking, etc., and it simply does nothing. Reinstalled Atom and Github Desktop, several times actually with different degrees of removing the pieces left over by the uninstall, but bo luck. I did my best to google the issue, but still no luck.
Funny thing though, on another laptop, Win 10, same versions for Atom and the Github Desktop, same installation procedure (first Atom then the Desktop) opening the repository in Atom worked fine from the first attempt, though it takes a while.

### Version

**GitHub Desktop version:** 1.04

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Install Atom (x64)
2. Install Github Desktop (x64)
3. Clone a Wiki repository from, say Gitlab (*.wiki.git)
4. Try to open the repository in Atom.

**Expected behavior:** The repository should open in Atom.

**Actual behavior:** Nothing. The repository doesn't open in Atom.

**Reproduces how often:** Every time.

### Logs
2017-10-22T16:36:35.660Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)
2017-10-22T17:28:56.706Z - info: [ui] [AppStore] loading 1 repositories from store
2017-10-22T17:28:56.708Z - info: [ui] [AppStore] found account: empgithub (null)
2017-10-22T17:28:56.967Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)
2017-10-22T17:47:13.693Z - info: [ui] [AppStore] loading 1 repositories from store
2017-10-22T17:47:13.695Z - info: [ui] [AppStore] found account: empgithub (null)
2017-10-22T17:47:13.882Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)
2017-10-22T18:13:25.055Z - info: [ui] [AppStore] loading 1 repositories from store
2017-10-22T18:13:25.057Z - info: [ui] [AppStore] found account: empgithub (null)
2017-10-22T18:13:25.251Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)

**Comment by shiftkey** [comment]
@empgithub can you open a PowerShell prompt, run these commands and attach the output:

```
> Get-Item HKCU:\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom
> $env:PATH
> gci $env:LOCALAPPDATA\\atom\\bin
```

I suspect something is off with the installation, and these are the things that Desktop will check to ensure it can find your Atom installation.

**Comment by empgithub** [comment]
@shiftkey: I checked these before posting the original message, and at least to my understanding, they seem OK and the "open in atom" command in the GitHub Desktop should work. Anyway, here are the outputs for the requested commands:

1. > Get-Item HKCU:\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom

PS C:\Users\Mihnea Popescu> Get-Item HKCU:\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom


    Hive: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall


Name                           Property
----                           --------
atom                           DisplayIcon          : C:\Users\Mihnea Popescu\AppData\Local\atom\app.ico
                               DisplayName          : Atom
                               DisplayVersion       : 1.21.1
                               InstallDate          : 20171022
                               InstallLocation      : C:\Users\Mihnea Popescu\AppData\Local\atom
                               Publisher            : GitHub Inc.
                               QuietUninstallString : "C:\Users\Mihnea Popescu\AppData\Local\atom\Update.exe"
                               --uninstall -s
                               UninstallString      : "C:\Users\Mihnea Popescu\AppData\Local\atom\Update.exe"
                               --uninstall
                               URLUpdateInfo        :
                               EstimatedSize        : 137331
                               NoModify             : 1
                               NoRepair             : 1
                               Language             : 1033

2. $env:PATH


PS C:\Users\Mihnea Popescu> $env:PATH
C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Python27\;C:\Program Files\Python27\Scripts;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Wi
ndows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Inte
l\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;
C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Skype\Phone\;C:\Users\Mihnea Popes
cu\AppData\Local\Microsoft\WindowsApps;C:\Users\Mihnea Popescu\AppData\Local\atom\bin;C:\Users\Mihnea Popescu\AppData\Local\GitHubDesktop\bin

3. gci $env:LOCALAPPDATA\\atom\\bin

PS C:\Users\Mihnea Popescu> gci $env:LOCALAPPDATA\\atom\\bin


    Directory: C:\Users\Mihnea Popescu\AppData\Local\atom\bin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        22-Oct-17     18:02             68 apm
-a----        22-Oct-17     18:02             65 apm.cmd
-a----        22-Oct-17     18:02             75 atom
-a----        22-Oct-17     18:02             58 atom.cmd

**Comment by shiftkey** [comment]
@empgithub those all look like the Atom installation is correct.

There may be some debug messages in the dev tools that aren't dumped to our log files - could you try the steps again, the click the **View** | **Toggle Developer Tools** menu item, switch to the **Console** tab and set the filter to **Verbose**:

<img width="984" src="https://user-images.githubusercontent.com/359239/31917187-7d0c6954-b899-11e7-8460-dab1be9530ab.png">

**Comment by empgithub** [comment]
@shiftkey I know they look ok, as I said I did my due diligence before posting the issue. And funny thing, they look identical to the ones on the laptop where the open in atom command in the github desktop actually works.

Two things, most likely originating from the fact that I am not a programmer and I am actually new to this Desktop/Atom thing.
(a) Not clear to me what steps you would like me to repeat. Please specify if something else than below.
(b) Got into the Desktop, opened it, switched to View, toggled Dev Tools on, switched to Console, in Console switched to Verbose. A window opened with the information below. Then I tried to open the project in atom, and the last line in the paste below showed up, saying some registry key is missing. Tried again to open the project in atom, but nothing happened, no other line got logged.

install.ts:31 [AppStore] loading 1 repositories from store
install.ts:31 [AppStore] found account: empgithub (null)
install.ts:35 Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z
install.ts:35 Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes
install.ts:35 Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
app.tsx:185 App ready time: 3754.353680998087ms
app.tsx:186 Load time: 806.4101950004697ms
app.tsx:187 Renderer ready time: 293.615ms
install.ts:35 Executing getWorkingDirectoryDiff: git diff --no-ext-diff --no-index --patch-with-raw -z --no-color -- /dev/null VVP/P3-SOC-ROB-PL-003-ValidationVerificationPlan_old_24_10_2017.md
install.ts:35 Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --
install.ts:35 Executing getRemotes: git remote -v
install.ts:35 Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT
install.ts:35 Executing getRemotes: git remote -v
install.ts:35 Executing installGlobalLFSFilter: git lfs install --skip-repo
install.ts:31 launching: 1.0.4 (Windows 10.0.15063)
install.ts:35 Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z
install.ts:35 Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes
install.ts:35 Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
install.ts:35 Executing getWorkingDirectoryDiff: git diff --no-ext-diff --no-index --patch-with-raw -z --no-color -- /dev/null VVP/P3-SOC-ROB-PL-003-ValidationVerificationPlan_old_24_10_2017.md
install.ts:35 Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --
install.ts:35 Executing getRemotes: git remote -v
install.ts:35 Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT
install.ts:35 Unable to find registry key - exit code 1 returned

**Comment by shiftkey** [comment]
@empgithub thanks for the new log!

> install.ts:35 Unable to find registry key - exit code 1 returned

This is interesting, and might be a clue. I've been discussing our registry access over in #3105 and it appears some group policy rules can interfere with our registry lookup.

Related to that issue - what shells do you have available?

**Comment by empgithub** [comment]
@shiftkey I know it is a clue, as you mentioned it, this is the reason I pointed it out. I looked over your reference, and didn't get something useful (for me) from it. I have no intention to open the project in some shell, I just want to open it in Atom.

First to answer your question. In terms of shells, I have on the machine whatever Windows 10 ships by default, which I suppose it is the standard Command Prompt cmd and the Power Shell (powershell). In the Github Dektop, in File/Options/Advanced/Shells it only shows Command Prompt. I tried to open the project in this shell, but I am getting what I suspect is the standard error message telling me I need to install Git if I want to be able to use Git commands, or else open without Git. And since I have no intention whatsoever to use Git commands in the cmd shell, I just left it be without installing Git.

And just to be on the safe side, I opened the Desktop as admin (suggestion in the ref you posted), and tried to open my repository in Atom. It didn't work.

Anyway, maybe a bit of the history of my tinkering with the Desktop would be useful. During my initial attempts to install the Desktop, I found out after the Desktop installation that I need to install FIRST Atom for the command to run. So I tried to uninstall the client, install Atom, and then reinstall the client. Of course, no success, and after some digging on the net, I found that in order to possibly solve the issue, I now have two problems on my hands (clean reinstall of both Atom and the Desktop) instead of one (just cleanly reinstalling of the Desktop). After more searching on the web, I ended up deleting some of the Atom or Desktop registry keys (don't remember which ones) together with the standard junk folders left on the drive, used CCleaner for the registry, and reinstalled Atom and the Desktop. Of course, there was no change, Open in Atom still didn't work from the Desktop. And that's when I decided to post my plight. 

On my other machine where the Open in Atom command works, and given the experience with the installation on this machine,  form the very beginning I installed Atom first, and then the Desktop. And it worked from the first attempt. So if I where to put in my two cents, I would say a clean reinstall of the two should solve the problem, but then based on my previous experience, there isn't any clear and comprehensive procedure for performing such a clean reinstall. Or at least I did not find one, just partial information in the effort of fixing other issues.

**Comment by shiftkey** [comment]
> In terms of shells, I have on the machine whatever Windows 10 ships by default, which I suppose it is the standard Command Prompt cmd and the Power Shell (powershell). In the Github Dektop, in File/Options/Advanced/Shells it only shows Command Prompt. 

This is promising, as it's the same thing as I found when I enabled this group policy on a test machine.

One thing to try is run this command:

```
$ C:/Windows/System32/reg.exe QUERY "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom"
```

On my machine, I get a helpful error message:

```
C:\Users\shiftkey>C:/Windows/System32/reg.exe QUERY "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom"
ERROR: Registry editing has been disabled by your administrator.
```

If you also get that, once we get #3209 merged you should be good to go.

With that PR, I now see under the **File** | **Options** dialog with the **Advanced** tab these options:

<img width="483" src="https://user-images.githubusercontent.com/359239/32258588-6c1aaed6-bf0f-11e7-85ec-0d5e0339ec70.png">

> And just to be on the safe side, I opened the Desktop as admin (suggestion in the ref you posted), and tried to open my repository in Atom. It didn't work.

Don't worry about that. It doesn't seem to work for me either. 

> On my other machine where the Open in Atom command works, and given the experience with the installation on this machine, form the very beginning I installed Atom first, and then the Desktop. And it worked from the first attempt. 

This seems fine - it's just identifying the variables between the two machines, and group policy still fits with everything else I've seen so far from this issue.

**Comment by empgithub** [comment]
@shiftkey sorry, was out of office last week.

Ran your command in both cmd and powershell (standard and admin) and got the following output:
C:\Users\Mihnea Popescu> C:/Windows/System32/reg.exe QUERY "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom"
ERROR: Invalid key name.
Type "REG QUERY /?" for usage.

So I don't quite get your output. What's next?

**Comment by shiftkey** [comment]
@empgithub can you use double-quotes in the string? I think that's what the error is complaining about...

**Comment by empgithub** [comment]
@shiftkey I did use the double backslash, for some reason it got transformed into single backslash when I pasted it in the body of the comment. I basically copied and pasted your string into both cmd and powershell. 

But let me show you something even funnier. I did my due diligence and re-ran your command in cmd. Here is the funny output.

C:\Users\Mihnea Popescu> C:/Windows/System32/reg.exe QUERY "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom"
ERROR: Invalid key name.
Type "REG QUERY /?" for usage.

This is the output that showed earlier, and which I mentioned in my previous post.

C:\Users\Mihnea Popescu>C:\Users\shiftkey>C:/Windows/System32/reg.exe QUERY "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom"
Access is denied.

This is the output I got for the same command now. Strange.

**Comment by empgithub** [comment]
@shiftkey I pasted your command into cmd and powershell, so it got run with the double double backslash. Somehow the double backslash vanished when I pasted the output in the postboard. Let me try to do it again. Here is the output:


C:\Users\Mihnea Popescu>C:/Windows/System32/reg.exe QUERY "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom"
ERROR: Invalid key name.
Type "REG QUERY /?" for usage.

At least before posting the comment, the double backslashes are in place.

**Comment by empgithub** [comment]
@shiftkey And they vanish after posting the message. So that solves the double backslash issue. We are still left with the main one.

**Comment by empgithub** [comment]
Just as a cross-check. The HKey in your string is there on the machine, I checked it manually using regedit. Not sure if it is of any help, but here is its content:

Key Name:          HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\atom
Class Name:        <NO CLASS>
Last Write Time:   26-Oct-17 - 16:46
Value 0
  Name:            DisplayIcon
  Type:            REG_SZ
  Data:            C:\Users\Mihnea Popescu\AppData\Local\atom\app.ico

Value 1
  Name:            DisplayName
  Type:            REG_SZ
  Data:            Atom

Value 2
  Name:            DisplayVersion
  Type:            REG_SZ
  Data:            1.21.1

Value 3
  Name:            InstallDate
  Type:            REG_SZ
  Data:            20171026

Value 4
  Name:            InstallLocation
  Type:            REG_SZ
  Data:            C:\Users\Mihnea Popescu\AppData\Local\atom

Value 5
  Name:            Publisher
  Type:            REG_SZ
  Data:            GitHub Inc.

Value 6
  Name:            QuietUninstallString
  Type:            REG_SZ
  Data:            "C:\Users\Mihnea Popescu\AppData\Local\atom\Update.exe" --uninstall -s

Value 7
  Name:            UninstallString
  Type:            REG_SZ
  Data:            "C:\Users\Mihnea Popescu\AppData\Local\atom\Update.exe" --uninstall

Value 8
  Name:            URLUpdateInfo
  Type:            REG_SZ
  Data:            

Value 9
  Name:            EstimatedSize
  Type:            REG_DWORD
  Data:            0x21873

Value 10
  Name:            NoModify
  Type:            REG_DWORD
  Data:            0x1

Value 11
  Name:            NoRepair
  Type:            REG_DWORD
  Data:            0x1

Value 12
  Name:            Language
  Type:            REG_DWORD
  Data:            0x409

**Comment by shiftkey** [comment]
@empgithub that's really strange behaviour from `reg.exe` - sounds like moving away from it in #3209 will also address this for you. Thanks for the additional troubleshooting!

**Comment by empgithub** [comment]
@shiftkey I cheched the group policy manually on my machine, and indeed the setting preventing access to registry editing tools is in place as described in #3209. But now I am at a loss. What am I supposed to do to fix it? As I mentioned earlier, I am not a programmer, so after reading the #3209 I don't feel any wiser. Please do advise.

**Comment by shiftkey** [comment]
> What am I supposed to do to fix it? As I mentioned earlier, I am not a programmer, so after reading the #3209 I don't feel any wiser. Please do advise.

You shouldn't have to do anything. I just need to wrap up the PR and get it out in an update.

**Comment by shiftkey** [comment]
Closing this out as it's the same root cause as #3105 and is being addressed in #3209

**Comment by empgithub** [comment]
@shiftkey Did you by any chance release the update you mentioned earlier? I updated just a few mins ago the Github client, and the Open in Atom feature is still now working.

**Comment by empgithub** [comment]
@shiftkey Did you by any chance release the update you mentioned earlier? I updated just a few mins ago the Github client, and the Open in Atom feature is still not working.

**Comment by joshaber** [comment]
No, the fix hasn't gone out in a release yet. You can follow along with our progress in https://github.com/desktop/desktop/pull/3209.

**Comment by cjcornell** [comment]
I have this same issue - so far been trying for 3-4 hours on 2 different windows machines ... ridiculous.
in an endless loop of opening Github desktop - external editor "none installed - install Atom" - click to install Atom ... about an hour later ... after Atom is Open ... " I try to open Github Desktop to view with external editor ... same thing ... not installed - try instaalling atom.
I have tried uninstalling and resintalling.  restarting apps.. rebooting, standing on one foot and chanting .. nothing seems to work.
Not sure what the point of having Github Desktop if I can't edit (or merge - since apparently Atom is require merge.
I emailed Github support (since I am a pro member) ... and all they said was "it should work, try again" ..  and later sent me some troubleshooting (e.g, just try these simple 72 steps ... )
ugh

**Comment by tierninho** [comment]
@cjcornell Sorry to hear this is happening. Do you mind filing on a new issue so we can investigate?

Please include the output of this terminal command in your issue: `mdfind kMDItemCFBundleIdentifier = "com.github.atom"`

I had a similar experience. I trashed Atom, reinstalled a fresh copy, then restarted Desktop.

**Comment by cjcornell** [comment]
"Please include the output of this terminal command in your issue: mdfind kMDItemCFBundleIdentifier = "com.github.atom""
I have no idea what that means .... (if I did, I wouldn't be trying to get the desktop version running : )
this is the second machine I've had to jump through all sorts of hoops getting Atom to work.  (and honnesstly - this editor it an awful choice!  seriously).
anyway ...
the support folks emailed me to try this in the command line:
cd %LOCALAPPDATA%\Atom\
atom --squirrel-updated

No miracles ... it did not work right away. But then after two more uninstalls and installs and reboots etc .... it worked.  So ... hell .. I have no idea why it finally got installed and integrated.
