### ISSUE TITLE
Asking to publish repo on desktop, even though it already exists

### ISSUE THREAD

**Issue by TheRedSpy15** [desktop/desktop#3723]
### Description

Trying to push an update to a branch on my repo, and I keep getting an error window for each change. It's also thinking that the repo doesn't exist and asking if I want to publish the repo

### Version

**GitHub Desktop version:** [1.0.11]

**OS version:** Windows 10.0.16299

### Steps to Reproduce

1. [open local folder through client]
1. [Delete and replace files]
1. [close window]

**Expected behavior:** [Show changes made to branch, and option to push the commit]

**Actual behavior:** [error windows, several all right after each other]

**Reproduces how often:** [everytime]

**Comment by TheRedSpy15** [comment]
**Logs**

[2018-01-04.desktop.production.log](https://github.com/desktop/desktop/files/1602514/2018-01-04.desktop.production.log)

**Comment by shiftkey** [comment]
@TheRedSpy15 thanks for the details. It appears to be that every attempt to spawn Git is errorring with the same exit code: 

```
2018-01-04T05:33:03.632Z - error: [ui] `git status --untracked-files=all --branch --porcelain=2 -z` exited with an unexpected code: 3221227782.
```

That exit code doesn't look familiar to me at first glance.

Could you try uninstalling Desktop, clearing `%LOCALAPPDATA%\GitHubDesktop\` and installing again to see if it's repeatable?

**Comment by TheRedSpy15** [comment]
I have uninstalled and reinstalled, and the issue persists

Strangely, I was automatically signed in when I reinstalled it

I did sign out and sign back in manually

and that didn't fix it either

**Comment by TheRedSpy15** [comment]
I'm gonna try another version, and post here with my findings

**Comment by shiftkey** [comment]
> Also, could you provide me with a more complete file path, I wasn't able to find it

The install location for GitHub Desktop is found `C:\Users\{name}\AppData\Local\GitHubDesktop\` where `{name}` is your account name

> Strangely, I was automatically signed in when I reinstalled it
> I did sign out and sign back in manually

This is because Electron apps will store their user data (not the install files) under `%APPDATA%`, so it is isolated from application updates.

**Comment by TheRedSpy15** [comment]
Ok, apparently my appdata folder was marked as hidden (no idea why)

I deleted the folder inside appdata\local and the repo folder under documents, and to top it off, I reinstalled it again

And I still have the issue

I also get errors when trying to clone the repo through the client

Is there a way for me to get a installer for 1.0.12 beta? or even 1.0.10?

**Comment by tierninho** [comment]
> 1.0.10

https://s3.amazonaws.com/github-desktop/releases/1.0.10-8910675f/GitHubDesktopSetup.exe

**Comment by TheRedSpy15** [comment]
Hm, with 1.0.10, I get this error when trying to clone my repo form github

"WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
fatal: could not create leading directories of 'C:\Users\Hunter\Documents\GitHub\The-Trail': No such file or directory
Error(s) during clone:
git clone failed: exit status 128"

**Comment by TheRedSpy15** [comment]
Hm, with 1.0.10, I get this error when trying to clone my repo form github

"WARNING: 'git lfs clone' is deprecated and will not be updated
with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
fatal: could not create leading directories of 'C:\Users\(USERNAME)\Documents\GitHub\The-Trail': No such file or directory
Error(s) during clone:
git clone failed: exit status 128"

EDIT: It updated, and still having the issue I did before with 1.0.11

What are the locations of every single file the client generates? It still automatically signed me in, and I would like to make sure I'm deleting everything

**Comment by OiYouYeahYou** [comment]
This may be a different case, but I can reproduce this issue by having non-matching remotes.

@TheRedSpy15 - On a terminal in the problem git repo if you enter the command `git remote -v` are the URLs identical or differing?

**Comment by TheRedSpy15** [comment]
Late reply, been busy

@OiYouYeahYou 

I don't have git on my PC

**Comment by shiftkey** [comment]
> I feel my issue can be resolved, if I knew where all the folders/files that are created by the client were

These are documented [here](https://github.com/desktop/desktop/blob/master/docs/installation.md#data-directories).

> does it leave user data in the window's registry?

Two protocol handler is created so that "Clone in Desktop" works and the authentication callback from the browser work. If you search for the `x-github-client`and `x-github-desktop-auth` keys you should find these. I don't think they're related to this issue though.

**Comment by TheRedSpy15** [comment]
Alright, I deleted every single one of those folders

recreated GitHub folder in documents

and get this error when trying to clone a repo:

"fatal: could not create work tree dir 'C:\Users\Hunter\Documents\GitHub\The-Trail': No such file or directory"

I will say, we made some progress, it did not sign me in automatically this time

**Comment by TheRedSpy15** [comment]
[2018-01-08.desktop.production.log](https://github.com/desktop/desktop/files/1610442/2018-01-08.desktop.production.log)

**Comment by TheRedSpy15** [comment]
Fixed it!

the client i guess doesn't play so well with windows 10's controlled folder access 

turned it off and everything worked perfectly

strangely, the CFA wasn't protecting anything that the client would be touching

**Comment by shiftkey** [comment]
> the client i guess doesn't play so well with windows 10's controlled folder access

Aha! This came up a while ago through our support channel, and we couldn't figure out a way to get Desktop to be whitelisted with Controlled Folder Access.

I'm glad you were able to workaround this!

**Comment by logger24** [comment]
Four years later and still happening... v,3.0.5

It was working fine, and then one day stopped and is trying to force me to publish a main branch.

**Comment by Jamal-Randolp** [comment]
Yes
