### ISSUE TITLE
Cannot pull after cloning a truly empty repository

### ISSUE THREAD

**Issue by MCF** [desktop/desktop#4574]
## Description

If you clone a truly empty repository (no files, no commits yet) from an SSH source github desktop will not let you pull or fetch.  The normal pull/fetch/push tab shows the message "cannot publish unborn head" and does nothing.  The push and pull menu items in the _Repository_ menu are disabled.

If someone else adds files and commits to the remote repository you cannot subsequently do a pull or fetch to pull them in via github desktop.  Obviously you can drop into command line git to do so but this does not seem like an advanced use-case that would require git to solve.

## Version

* GitHub Desktop: 1.1.1
* Operating system: Windows 7, 64 bit

## Steps to Reproduce
Clone an empty repository (no commits) from an SSH source

### Expected Behavior
You would still be able to pull/fetch from the remote.

### Actual Behavior
Pull/fetch is disabled (apparently) through all controls.

### Logs
Nothing relevant in the logs.

**Comment by shiftkey** [comment]
@MCF thanks for the report. I've been able to reproduce this, and I think it's down to how we handle the unborn repository.

The behaviour for this button is in [`push-pull-button.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/toolbar/push-pull-button.tsx), and I'll come back to this later to add more details if someone is interested in contributing a fix.

**Comment by shiftkey** [comment]
A rough patch for this:

```diff
diff --git a/app/src/ui/toolbar/push-pull-button.tsx b/app/src/ui/toolbar/push-pull-button.tsx
index ac499b989..2c6370f1e 100644
--- a/app/src/ui/toolbar/push-pull-button.tsx
+++ b/app/src/ui/toolbar/push-pull-button.tsx
@@ -68,7 +68,8 @@ export class PushPullButton extends React.Component<IPushPullButtonProps, {}> {
     // open the publish dialog - we'll handle publishing the current branch afterwards
     // if it exists
     const validState = this.props.remoteName
-      ? this.props.tipState === TipState.Valid
+      ? this.props.tipState === TipState.Valid ||
+        this.props.tipState === TipState.Unborn
       : true
 
     const disabled = !validState || networkActive
@@ -127,6 +128,13 @@ export class PushPullButton extends React.Component<IPushPullButtonProps, {}> {
     if (!this.props.remoteName) {
       return 'Publish repository'
     }
+
+    // repository has a remote but no branch to manage
+    //  -> can fetch to see if someone else has pushed remote commits
+    if (this.props.tipState === TipState.Unborn) {
+      return 'Fetch'
+    }
+
     if (!this.props.aheadBehind) {
       return 'Publish branch'
     }
@@ -153,6 +161,11 @@ export class PushPullButton extends React.Component<IPushPullButtonProps, {}> {
     if (!this.props.remoteName) {
       return OcticonSymbol.cloudUpload
     }
+
+    if (this.props.tipState === TipState.Unborn) {
+      return OcticonSymbol.sync
+    }
+
     if (!this.props.aheadBehind) {
       return OcticonSymbol.cloudUpload
     }
@@ -180,7 +193,7 @@ export class PushPullButton extends React.Component<IPushPullButtonProps, {}> {
     }
 
     if (tipState === TipState.Unborn) {
-      return 'Cannot publish unborn HEAD'
+      return `Fetch ${this.props.remoteName}`
     }
 
     if (!this.props.aheadBehind) {
@@ -207,6 +220,11 @@ export class PushPullButton extends React.Component<IPushPullButtonProps, {}> {
     const dispatcher = this.props.dispatcher
     const aheadBehind = this.props.aheadBehind
 
+    if (this.props.tipState === TipState.Unborn) {
+      dispatcher.fetch(repository, FetchType.UserInitiatedTask)
+      return
+    }
+
     if (!aheadBehind) {
       dispatcher.push(repository)
       return
```

This feels suboptimal because we're repeating the same check in a few places, but that's a side-effect of how the component is currently organized. But that should be a starting point for someone to dig into.

**Comment by sportshead** [comment]
If nobody's working on this issue, I'm going to try to have a poke at it.

**Comment by agisilaos** [comment]
@sergiou87, @niik I think this is now fixed based on the new way of defining components etc?

**Comment by steveward** [comment]
I'm going through old issues and confirmed this bug still exists in v3.2.0.

**Comment by samuelko123** [comment]
Hi @steveward , can I give it a try?
