### ISSUE TITLE
Branch list (compare tab) hides after specific pattern of keyboard events

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#5370]
## Description

Stumbled upon this while testing keyboard navigation for #5368 

## Version
* GitHub Desktop: `1.3.2-beta`
* Operating system: macOS 

## Steps to Reproduce
1. Open the compare tab, and focus on the filter textbox
2. Press Down to select first branch
3. Press Up to select filter textbox
4. Press Down to select first branch again

### Expected Behavior
Branch list is visible and first branch is selected, ready to confirm

### Actual Behavior
Branch list is hidden

## Additional Information

Here's a GIF:

![branch-selector-hides](https://user-images.githubusercontent.com/359239/43964582-82e88b62-9c93-11e8-8d09-6c399d367983.gif)

I'm also not sure why the list "jumps" a bit after keying down to focus on the first branch.

**Comment by ADustyOldMuffin** [comment]
@shiftkey So can you still reproduce this? I don't get the same issue with windows, but the result is still... odd.

![GithubDesktopReproduce](https://user-images.githubusercontent.com/41391321/58664476-528b4200-82f4-11e9-8d5f-0ec02a8d25b5.gif)

I'm pressing down the entire time and my selection never changes it just scoots the focused window down and it acts like a spring almost.

**Comment by shiftkey** [comment]
@ADustyOldMuffin I'm not sure.

It's been a while since I opened this, but I'll re-test this tomorrow and see what work needs to be done in here.

**Comment by ADustyOldMuffin** [comment]
@shiftkey Any progress on reproducing?

**Comment by ADustyOldMuffin** [comment]
On the windows side I think this works as intended now and got fixed by something else.

**Comment by shiftkey** [comment]
@ADustyOldMuffin I wasn't able to trigger the original behaviour, but I'm still not happy with this interaction. On macOS here's how I set it up:

1. Open the compare tab, and focus on the filter textbox
2. Press Down to select first branch

At this point you retain keyboard focus on the filter textbox, but the first item in the list of branches is selected. Pressing down at this point triggers a scroll event, but the selection doesn't change and you stay at the top of the list. Pressing up does nothing.

**Comment by shiftkey** [comment]
I've opened #7802 to indicate what the current behaviour is and what should occur, rather than continue to work with this stale issue.
