### ISSUE TITLE
Creating repo on GitHub works fine, but cannot push any edited files. (Mac)

### ISSUE THREAD

**Issue by IrvKalb** [desktop/desktop#6007]
## Description

Created  a repository on my local computer (Mac).  Opened GitHub Desktop,  added the local repository.  Committed.  Pushed to GitHub.  Filled out dialog box naming the repository on GitHub.  Everything worked fine.

Made a change to a local file. Went to GitHub Desktop, saw that the change was recognized.  Committed the change.  Tried to push change to GitHub.  Brought up the same dialog box asking to publish the entire directory.  

I expected that the single file would be updated in my GitHub repository.  

I tried clicking on "Publish Directory", but got an error message saying that a directory by that name already exists.  

## Version

* GitHub Desktop:  Mac 1.4.3
git rev-parse HEAD
0769c64be561b2ca57d1c94f702f6ec93dbad915

* Operating system: Mac 10.12.6

## Steps to Reproduce

1. Create local repo
2. Open GitHub Desktop
3. Select Add Local Repository
4. Commit
5. Push to GitHub
6. Fill out Dialog Box with GitHub repo name
7. Confirm Github repo with proper name exists
8. Make a change to a file in the local repo
9. Go to GitHub
10. Verify change is recognized, 1 file changed
11. Commit the change
12. Attempt to push the change to GitHub.

The GitHub repo is:  IrvKalb/pyghelpers

### Expected Behavior

Single file should be updated in GitHub repo

Also: I expect to see my repo listed under "GitHub.com" in the left panel

### Actual Behavior

GitHub Desktop asks me to publish full repo, and asks for name.
If I give the same name, I get a message saying that a repo by this name already exists.

The repo name shows up under "Other" in the left panel

## Additional Information

![image](https://user-images.githubusercontent.com/7294026/47588950-9a8c5580-d91c-11e8-9166-2da0ec305dfb.png)

I will go through the steps again right now to show the dialog box I am seeing.  All I did was to add a blank line at the bottom of my file.  And, I have now tried this three times (in this screenshot, you can see the number 3 by the Push origin button).

![image](https://user-images.githubusercontent.com/7294026/47589188-4b92f000-d91d-11e8-8f13-33aab41f254e.png)

I spoke with a friend who is an expert at using git through the command line, and he told me that the local repo was set up correctly.

Also, I have another repo (IrvKalb/pygwidgets) which was set up the same way, and that repo is working perfectly with GitHub Desktop.

Please let me know if there is any more information I can supply:  Irv@furrypants.com

### Logs

[2018-10-26.desktop.production.log](https://github.com/desktop/desktop/files/2520646/2018-10-26.desktop.production.log)

Thank you.

**Comment by shiftkey** [comment]
@IrvKalb thanks for the report. I think this is the same as an earlier report https://github.com/desktop/desktop/issues/5936 which I believe has been fixed in #5948 which we just published to our beta channel today.

If you'd like to try it out, the details about our beta channel are available here: https://github.com/desktop/desktop#beta-channel

**Comment by IrvKalb** [comment]
Thanks for your quick response.

I've downloaded the beta version (1.5.0-beta1) and opened it.  When I open it, I still see my GitHub repo listed under  "Other", and clicking on the "Push Origin" button (with a 3 and an up arrow) still brings up the "Publish Repository" dialog box.

Can you tell me what steps I should take to test out this version?  (I'm very new to the world of git & GitHub Desktop, so I need details.)

**Comment by steveward** [comment]
@IrvKalb I had one other user resolve a similar issue by removing the repository from GitHub Desktop and then adding it back. Could you try doing that to see if it gets things working for you?

**Comment by IrvKalb** [comment]
Seemed like a reasonable thing to try.  I removed the "pyghelpers" repository (leaving only my other "pygwidgets" repository):

![image](https://user-images.githubusercontent.com/7294026/47730709-f2c69e80-dc1f-11e8-9f34-e63f4a123d23.png)

Then I did an Add Local Repository ...  to add it back in.  But it came back under "Other", just like before:

![image](https://user-images.githubusercontent.com/7294026/47730796-2275a680-dc20-11e8-9a1b-6def2930f4ad.png)

When I look at the resulting repository settings, it looks fine:

![image](https://user-images.githubusercontent.com/7294026/47730897-581a8f80-dc20-11e8-81d5-7e2bb8819d1c.png)


The good news is that when I do a push - it does seem to work now!

However, I'm still still confused as to why the "pyghelpers" is listed under "Other" while my other repository is listed under "GitHub.com".  I would expect that both would be listed under "GitHub.com".

**Comment by IrvKalb** [comment]
(I just updated to the newest beta 2 version of GitHub Desktop)

Perhaps I spoke to soon.  I just made a change to a file, committed the change, and tried to push.  I got the same "Publish Repository" dialog box.

![image](https://user-images.githubusercontent.com/7294026/47826247-f21f2c80-dd33-11e8-922b-a7511aa39a68.png)

**Comment by IrvKalb** [comment]
I saw that there was a new beta version available, so I upgraded.

I tried removing the local repository, then adding the local repository.  The repository still comes in under "Other"

![image](https://user-images.githubusercontent.com/7294026/48238310-6040a080-e37f-11e8-8822-8201bf143c39.png)

Even though when I do a Repository Settings, it has the correct URL for my GitHub repository.

**Comment by IrvKalb** [comment]
A little more info from testing today (with Version 1.5.1-beta0)

I have two local repositories:  pygwidgets and pyghelpers.  pygwidgets works fine, but pyghelpers demonstrates this bug.

I tried removing both.  Then added back pyghelpers first - trying to see if the problem is with a second repository.  When I do that, pyghelpers shows up under the title "Other".  Adding back pygwidgets shows up under the title "GitHub.com".

So the problem remains that one of my local repositories shows up under "Other" independent of the order that they are added, and that repository will not push updates to GitHub.

**Comment by IrvKalb** [comment]
Please let me know if there is any information I can supply to help track down this problem.

**Comment by steveward** [comment]
@IrvKalb apologies for the delay. 

> and that repository will not push updates to GitHub.

Does the `pyghelpers` repository correctly point to the remote repository on GitHub? You can check this by going to the file menu and selecting `Repository` > `Repository settings` > `Remote`. 

The other step you can try would be to reset Github Desktop back to a fresh state to see if that resolves this issue. You can do this by following these steps:

1. Close GitHub Desktop
2. Open Terminal.app
3. Run the command `rm -r ~/Library/Application\ Support/GitHub\ Desktop`
4. Launch GitHub Desktop and then log in and add your repositories again

Let me know if that helps.

**Comment by IrvKalb** [comment]
1)  Yes, the pyghelpers respository correctly points to the remote repository on GitHub:   https://github.com/IrvKalb/pyghelpers.git

2)  FIXED!!!

I gave the rm command, re-opened GitHub Desktop and added the repositories again.  They both came in under the GitHub.com heading.  I made a small change to a source file, and was able to check it in and push to GitHub.

Thank you very much!

(Can I ask you to explain what the problem was - or more importantly, is there anything I can do to prevent this problem from happening again?)
