### ISSUE TITLE
Error: Authentication failed

### ISSUE THREAD

**Issue by afbora** [desktop/desktop#7039]
![ss](https://user-images.githubusercontent.com/3393422/54015904-4038b680-4192-11e9-91fb-33a9b85fa8e1.jpg)

### Log
> 2019-03-08T08:07:50.470Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: SimpleTimeTracker - afbora (has token)
2019-03-08T08:07:51.923Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 1.377s)

### Description

I committed to repository yesterday successfully but i'm getting this issue now.
Sign out and sign in again but didnt work.

### Version
- GitHub Version 1.6.3
 - Windows 10 Pro x64 1809 Build 17763.316

**Comment by steveward** [comment]
Thanks for the report @afbora. Could you upload the log file from GitHub Desktop so that  I could take a closer look?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.

**Comment by afbora** [comment]
I already shared 2 lines from the log.
When i push the commit, just added these two lines.

**Comment by afbora** [comment]
@stevecat I launched the GitHub Desktop and push origin and here the today log:

> 2019-03-09T07:30:49.908Z - info: [ui] [AppStore] loading 1 repositories from store
2019-03-09T07:30:49.909Z - info: [ui] [AppStore] found account: afbora (Ahmet Bora)
2019-03-09T07:30:50.182Z - info: [ui] launching: 1.6.3 (Windows 10.0.17763)
2019-03-09T07:30:50.182Z - info: [ui] execPath: 'C:\Users\BORA\AppData\Local\GitHubDesktop\app-1.6.3\GitHubDesktop.exe'
2019-03-09T07:30:51.926Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.261s)
2019-03-09T07:30:52.002Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.382s)
2019-03-09T07:31:01.013Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: SimpleTimeTracker - afbora (has token)
2019-03-09T07:31:03.460Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 2.353s)

**Comment by afbora** [comment]
I'm still getting on commit and following error while publishing branch on version 1.6.4

![Ek Açıklama 2019-03-13 152614](https://user-images.githubusercontent.com/3393422/54278817-892ea780-45a4-11e9-9f0f-4a65bb2fe60b.jpg)

![Ek Açıklama 2019-03-13 152635](https://user-images.githubusercontent.com/3393422/54278826-8df35b80-45a4-11e9-9511-026ff2b59421.jpg)

**Comment by afbora** [comment]
I changed the repository remote url "https to http" and "https to ssh" but didnt work.

**Comment by steveward** [comment]
@afbora is this issue happening in all repositories you are trying to push to in GitHub Desktop, or just one specific repository?

**Comment by afbora** [comment]
@steveward All repositories.

I cloned the new own repository to locale with GitHub Desktop just before.
Just updated the composer.json file and commited to master.
I got same error as "Authentication failed".

**Comment by steveward** [comment]
@afbora I would try resetting GitHub Desktop to see if that helps. You will need to log in and add your repositories again after performing these steps:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop 

Let me know if that helps at all with this issue.

**Comment by afbora** [comment]
@steveward I deleted all files in "C:\Users\USERNAME\AppData\Local\GitHubDesktop" following list:

![Ek Açıklama 2019-03-15 122918](https://user-images.githubusercontent.com/3393422/54421812-3c6edc00-471e-11e9-8674-876930d0f70f.jpg)

When i try to run Github Desktop, i got following error on Win10:

> The item that this shortcut refers to has been changed or moved, so this shortcut will no longer work properly. Do you want to delete this shortcut?

**Comment by afbora** [comment]
@steveward I deleted the GitHubDesktop folder again.
Downloaded GitHub Desktop v1.6.4 for Windows (64bit) and installed again.
Still same error throwing ://

**Comment by steveward** [comment]
@afbora it looks like you deleted the `%LocalAppData%\GitHubDesktop` directory, which has various application files. The cached data that GitHub Desktop stores lives in `%AppData%\GitHub Desktop`, which is short for `C:\Users\<Your_user>\AppData\GitHub Desktop`. Could you try deleting that directory?

**Comment by afbora** [comment]
@steveward You right. I was deleted application files.

Now i deleted right folder contents: "C:\Users\USERNAME\AppData\Roaming\GitHub Desktop".
Restarted the application and setup installation wizard.
Added local repositories and tried to push origin.
Same notification throwing and no error found in logs again :(

**Comment by steveward** [comment]
@afbora you had previously mentioned that you had changed the repository remote URL:

>I changed the repository remote url "https to http" and "https to ssh" but didnt work.

If you changed the remote URL to SSH then that could be causing this issue, since you would need a valid SSH key in order to authenticate and push. Can you verify that the repositories you are working with are using HTTPS?

**Comment by afbora** [comment]
@steveward It is HTTPS. I just want to try other connections.

**Comment by afbora** [comment]
@steveward Could this be a bug?

**Comment by steveward** [comment]
@afbora we are aware of authentication issues like this, but it's been difficult to track down what specifically is causing these problems on each individual machine. See https://github.com/desktop/desktop/issues/3816 for reference. 

One problem we have seen has been due to an invalid token, but everything in the log seems to point to your token being valid:

`2019-03-13T12:29:49.427Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: larathemes - afbora (has token)`

And we've already tried the log out/log in workaround, along with deleting the cached data GitHub Desktop stores.

Have you tried pushing to a repository using the command line to see if that is successful? 

One other thing you could check would be to open Windows `Credential Manager` > `Windows Credentials` to verify that the `GitHub - https://api.github.com/<username>` exists.

**Comment by afbora** [comment]
@steveward I tried your said and all is well.

1. Pushed successfully via command line: [Screenshot](https://user-images.githubusercontent.com/3393422/54667525-a19b4680-4afd-11e9-955e-e1dffc73f804.jpg)

2. Checked windows credential manager and it is exist: [Screenshot](https://user-images.githubusercontent.com/3393422/54667700-09519180-4afe-11e9-939d-834de6952ccf.jpg)

**Comment by mido1966** [comment]
Thank you everyone alles ok  Dankeschön alles ok

‏‫من الـ iPhone الخاص بي‬

‫في 19‏/03‏/2019 الساعة 9:58 م، كتب/كتبت ‏Steve Ward ‏<notifications@github.com<mailto:notifications@github.com>>:‬


@afbora<https://github.com/afbora> we are aware of authentication issues like this, but it's been difficult to track down what specifically is causing these problems on each individual machine. See #3816<https://github.com/desktop/desktop/issues/3816> for reference.

One problem we have seen has been due to an invalid token, but everything in the log seems to point to your token being valid:

2019-03-13T12:29:49.427Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: larathemes - afbora (has token)

And we've already tried the log out/log in workaround, along with deleting the cached data GitHub Desktop stores.

Have you tried pushing to a repository using the command line to see if that is successful?

One other thing you could check would be to open Windows Credential Manager > Windows Credentials to verify that the GitHub - https://api.github.com/<username> exists.

**Comment by EngineerAhmedMo** [comment]
i have the same problem

**Comment by tierninho** [comment]
Sounds like this is now resolved, so closing this issue. Happy to reopen if I was mistaken.

@EngineerAhmedMo Please open a new issue [here](https://github.com/desktop/desktop/issues/new?template=bug_report.md) and we will be happy to investigate.

**Comment by afbora** [comment]
@tierninho No, the issue is still continue. I haven't written in 22 days because nothing was done to fix and i shared all attempts and logs about the issue.

**Comment by steveward** [comment]
@afbora could you try creating a new user account on your current Windows machine with a fresh installation of GitHub Desktop? Then try authenticating and pushing from there to see if that works. That should help narrow down if an issue in your local user account is causing the clone to fail.

**Comment by afbora** [comment]
@steveward Here my steps:
1. Deleted all contents in %LocalAppData%\GitHubDesktop
2. Deleted all contents in %AppData%\GitHub Desktop
3. Downloaded fresh x64 file from desktop.github.com
4. Run installation file
5. Created new GitHub account
6. Created new repository
7. Signed in with new account on GitHub Desktop
8. Cloned the new repository
9. Clicked "Publish Branch" button (without any commits yet)
10. Failed with same error

> 2019-04-11T14:12:21.808Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: test - byybora (has token)
2019-04-11T14:12:23.425Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 1.532s)

**Comment by csalmeida** [comment]
This same issue happened to me after I've removed the older version of the app, when trying to do any actions would the new one it doesn't work. It was working before I removed it so I take it it has something to do with the `SSH` keys? 

This is issue is also described at #3816 and #4181.

**Comment by steveward** [comment]
@afbora thanks for those steps -- I actually meant for you to create a new user account on your Windows machine, not a new GitHub account. Apologies for not clarifying that. Would you be able to test that out? 

@csalmeida could you open up a new issue and fill out the template? Please make sure to also upload a log file.

**Comment by csalmeida** [comment]
> 
> 
> @afbora thanks for those steps -- I actually meant for you to create a new user account on your Windows machine, not a new GitHub account. Apologies for not clarifying that. Would you be able to test that out?
> 
> @csalmeida could you open up a new issue and fill out the template? Please make sure to also upload a log file.

Sure thing @steveward, thanks for looking into it. 🙏 Issue: #7384

**Comment by afbora** [comment]
@steveward I created new windows user account. Download and install new GitHub Desktop x64 app. Cloned a repository and tried to commit/publish branch and failed again with same authentication error. Added log file but no error again.

[2019-04-25.desktop.production.log](https://github.com/desktop/desktop/files/3116257/2019-04-25.desktop.production.log)

**Comment by afbora** [comment]
@steveward Still this is not a bug?

**Comment by steveward** [comment]
@afbora have you possibly modified the registry on your machine? Some users have reported modifying the command processor's AutoRun setting (`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor\Autorun`) has caused these authentication issues.

**Comment by afbora** [comment]
@steveward No, i didnt modify any registry settings. So why doesn't log on authentication error?

**Comment by afbora** [comment]
@steveward So interesting! I clicked the button "Open in Atom" in GitHub Desktop. I pushed commits with Atom and success.

**Comment by tierninho** [comment]
@afbora Curious if this is still an issue for you and have you upgraded to Desktop 2.0.4? Thanks.

**Comment by afbora** [comment]
@tierninho I have tested on v2.0.4 and still getting error as Authentication failed 👎

**Comment by tierninho** [comment]
Bummers 😞. These types of issues are difficult to track down as there are multiple factors that could be affecting this. At this point, but my suggestion would be to comb through the [list of authentication issues](https://github.com/desktop/desktop/issues?utf8=%E2%9C%93&q=is%3Aissue+Authentication) and see if one of the previous resolutions may help. Let me know how it goes and apologies for the continued disruption to your work.

**Comment by afbora** [comment]
@tierninho I still think this is a bug.

1. I created a commit and pushed origin successfully with CLI (First Commit)
2. I created a commit and pushed origin successfully with Atom (Second Commit)
3. I created a commit and push origin failed with Github Desktop (Third Commit)

**Comment by afbora** [comment]
I've readjusted all SSH information now, but nothing has changed. 

Can't we find an immediate solution? I can grant access to my device if necessary.

**Comment by steveward** [comment]
@afbora I just helped another GitHub Desktop user who was encountering this same issue, and we tracked down the issue to being caused by modified registry entries. in a previous comment you did not confirm whether or not you checked these registry entries, so I would recommend opening `regedit.exe` to verify nothing has been modified in these locations:

`HKEY_CURRENT_USER\Software\Microsoft\Command Processor\`
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor\`

If you see an `Autorun` entry in either of those locations then that is likely causing these authentication issues you are encountering. Since this error happened even after you created a new user on your Windows machine my hunch is that the `HKEY_LOCAL_MACHINE` entry may have been modified.

**Comment by afbora** [comment]
I owe you an apology 😞 Yes, I had not modified the registry, but I saw the `autorun` registration in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor\` now and everything worked great.

**Comment by afbora** [comment]
@steveward Will there be a new version about it?

**Comment by steveward** [comment]
@afbora I'm glad things are working for you now!

It would be nice if we could automatically detect this in the app, but for now I'm going to make a note to work on a PowerShell script to make it quicker to check if these registry entries have been modified. I have also added a section about this in our `known-issues.md` that we can reference -- https://github.com/desktop/desktop/pull/9069.  Thanks for your help here!

**Comment by damien-mattei** [comment]
hello
i have the same problem : here are the logs:

2020-03-08T09:26:19.207Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
2020-03-08T09:26:24.024Z - info: [ui] Current tutorial step is NotApplicable
2020-03-08T09:26:24.060Z - info: [ui] [BranchPruner] No branches to prune.
2020-03-08T09:26:25.622Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: library-FunctProg - damien-mattei (has token)
2020-03-08T09:26:26.898Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 1.262s)

any idea?

Damien

**Comment by damien-mattei** [comment]
my password was good in github desktop preferences but wrong in the .git/config file

for me the only working solution was to manually edit the file:
.git/config

that contains this line:
url = https://user:password@github.com/user/repo.git

change password to the GOOD password because it was an older one for me

**Comment by bopoh13** [comment]
@damien-mattei, thanks. This is _so far the only way_ to push origin in GitHub Desktop without additional applications. Instead of a password, you can create a https://github.com/settings/tokens
