### ISSUE TITLE
"Create a Pull Request" suggestion visible when PR already exists

### ISSUE THREAD

**Issue by zeke** [desktop/desktop#7309]
Hi friends! This is a very minor bug report.

I'm seeing a prompt to create a PR:

<img width="617" alt="Screen Shot 2019-04-15 at 8 51 03 PM" src="https://user-images.githubusercontent.com/2289/56180927-35a6e380-5fc0-11e9-889b-e72b20651d3a.png">

But a (draft) PR already exists:

<img width="686" alt="Screen Shot 2019-04-15 at 8 51 49 PM" src="https://user-images.githubusercontent.com/2289/56180944-5111ee80-5fc0-11e9-8efb-66ed80da35de.png">

Guesses about the possible cause:

- GitHub Desktop doesn't recognize Draft PRs as PRs
- Regression in beta version of GitHub Desktop

GitHub Desktop version: 1.7.0-beta2
OS version: macOS 10.14.3 Mojave

**Comment by shiftkey** [comment]
@zeke can you confirm whether the pull request is visible from the branch switcher? I gather it's not detecting there, but it'd be nice to nail down the places where we're not correctly detecting this draft PR:

<img width="392" src="https://user-images.githubusercontent.com/359239/56300605-a3f8bc80-610c-11e9-99b9-771c73f5d042.png">

**Comment by zeke** [comment]
Update: Apparently this issue is not unique to draft PRs; I've changed the issue title to reflect that. 

There's a prompt to create a new PR, and there's no PR listed in the branch switcher:

--- 

<img width="749" alt="Screen Shot 2019-04-22 at 4 00 22 PM" src="https://user-images.githubusercontent.com/2289/56538434-e1e44f00-6517-11e9-9708-4b28c28f4b21.png">

--- 

But the PR does exist: 

--- 

<img width="684" alt="Screen Shot 2019-04-22 at 4 02 44 PM" src="https://user-images.githubusercontent.com/2289/56538632-6f27a380-6518-11e9-90ff-3ff019d2b130.png">

--- 

Note: This happened after I did a (successful) [Pull Origin] and [Push Origin] within Desktop. Before I did that, the create-a-PR prompt was not there (expected behavior), and the PR was visible in the 
branch switcher (also expected behavior).

PS I'm on macOS 1.7.0-beta4

**Comment by zeke** [comment]
...and after I made a change, Fetched, and pushed (all in Desktop), things go back to normal:

<img width="730" alt="Screen Shot 2019-04-22 at 4 11 03 PM" src="https://user-images.githubusercontent.com/2289/56538958-5c619e80-6519-11e9-9bc5-2ee6a2a940fb.png">

**Comment by shiftkey** [comment]
@niik when you have a moment I'd love your thoughts here on what might be happening under the hood and if there's anything else that @zeke can provide here to help us understand this issue...

**Comment by agisilaos** [comment]
I encountered the same bug and was ready to submit it. Glad it was reported already.

**Comment by niik** [comment]
Hey all,

This is a known issue and something I'm working on fixing before the next production release. This particular suggestion is only turned on for the beta channel for this exact reason so it only affects users currently on the beta channel. The reason why it's still showing is simply that we don't stay up to date with the PR list on dotcom. Prior to https://github.com/desktop/desktop/pull/7027 there was only two ways to refresh the list of PRs; either switching repositories (which would trigger a reload of PRs 10 minutes after) or by clicking on the fetch button. The problem with the latter of course is that the fetch button won't be visible if your branch isn't published (which it won't be if you've deleted the branch when merging the PR).

I'll assign myself to this PR so y'all can see when we're ready to enable this suggestion for everyone.

**Comment by zeke** [comment]
Thanks for the info, @niik 

> The reason why it's still showing is simply that we don't stay up to date with the PR list on dotcom.

☝️This seems odd, considering that Desktop did at one point know about the PR in question, then later "forgot" about it.

**Comment by tierninho** [comment]
As #7501 is now on Beta, I am confirming that this issue has been resolved and the "PR next steps" no longer shows if a PR/draftPR is present.

**Comment by KnowledgeableKangaroo** [comment]
I am experiencing the same bug

**Comment by KnowledgeableKangaroo** [comment]
Please reopen this as it is the same as my issue which is referenced above. The update did not fix this because I am updated and am experiencing the same things.

**Comment by shiftkey** [comment]
> Please reopen this as it is the same as my issue which is referenced above. 

@KnowledgeableKangaroo this issue was opened for different reasons than what we are talking about in #7947, and there was work that landed in the 2.0 release to address it. Let's keep the discussion about additional work to #7947.
