### ISSUE TITLE
Adding commit after rebase results in merge instead of rebase

### ISSUE THREAD

**Issue by bvkatwijk-cleverbase** [desktop/desktop#8736]
### Describe the bug

After rebasing a branch without immediately pushing it, adding a commit will cause the rebase commit to become a merge commit instead.

### Version & OS

Version: 2.2.3
OS: macOS Mojave 10.14.6

### Steps to reproduce the behavior

1. Rebase current branch on mainline
2. Add a commit to current branch
3. Press Push/Pull button
4. Open History tab
    * The last commit is `Merge branch 'branchname'` of `github.com/branchname` into `branchname` instead of a rebase.

### Expected behavior

The last commit should be the commit added in step 2, and no merge commit should be present. The branch should have been rebased correctly.

### Actual behavior

The most recent commit is a merge commit, merging the (rebased?) remote branch into current local branch.

**Comment by tierninho** [comment]
@bvkatwijk-cleverbase Many thanks for the issue. I was unsuccessful at reproducing this.

Is it possible to include your logs and any screenshots?

Also, curious if you ran into any merge conflicts as part of the rebase?

**Comment by tierninho** [comment]
@bvkatwijk-cleverbase  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by bvkatwijk-cleverbase** [comment]
I was not able to reproduce the issue, one of my colleagues suggested it might have been an issue between my OS version and Git. Thanks!

**Comment by tierninho** [comment]
Thanks for the update. Glad it is resolved!

**Comment by Amitavam** [comment]
@tierninho  The issue is still there and constantly reproducible on version- 2.2.4, mac os- 10.13.6. 
I was about to raise a new issue then found this one.
