### ISSUE TITLE
App crashes on opening external file/cmd-clicking on it

### ISSUE THREAD

**Issue by dacarver** [desktop/desktop#8846]
When attempting to open a file in an external editor, the app crashes. This is very inconsistent. Sometimes it's when opening in an external editor, sometimes it's just when command-clicking on a modified file. It is occurring frequently. The steps below are one example of when it occurred, although I could then not reproduce it using the same steps.

This frequent crashing started after updating to 2.2.4.

GitHub Desktop version 2.2.4
MacOS version 10.15.2

1. Visual Studio Code set as the external editor in preferences
2. Make a change in a Podfile.lock file
3. Command-click on the file in the list and choose Open with Visual Studio Code 
4. Application crashes

**Comment by billygriffin** [comment]
Thanks @dacarver and sorry that’s happening for you! Would you mind sharing a log file from a day it’s occurring frequently? You can find them in “Help -> Show logs in Finder/Explorer” from the menu. Also, would you mind sharing your OS version? Thanks!

**Comment by dacarver** [comment]
@billygriffin Here is the log file from today when it happened a few times. Names and URLs have been replaced with `---` for security reasons

https://www.dropbox.com/s/hiz5yp1qkzn6dlq/2019-12-30.desktop.production.log?dl=0

**Comment by tierninho** [comment]
I do not see anything in the logs. Just to confirm, Desktop crashed and not Visual Studio Code? When Desktop crashes, it should show a window informing the user of the crash as implemented in #8405 Any chance you saw this? Regardless, i will try to reproduce soon.

**Comment by dacarver** [comment]
Correct, it's definitely Github Desktop that is crashing. The only dialog box that comes up is the system one, to send the crash report to Apple. I'll see if I can get any information from that dialog and provide it (think it gives a stack trace and some other information).

**Comment by dacarver** [comment]
<img width="434" alt="Screen Shot 2020-01-03 at 8 59 11 AM" src="https://user-images.githubusercontent.com/33436417/71733959-0531fe80-2e08-11ea-8db6-7a94a62dbfb1.png">

Here is the contents of the crash log that came up when this happened again. I went to "Open with default program" on a .swift file, which caused this.

https://www.dropbox.com/s/3mv0jmjryr2wv56/log.txt?dl=0

**Comment by tierninho** [comment]
@niik Any insight on this is appreciated.

**Comment by niik** [comment]
Hi @dacarver, thanks for opening this. My gut feeling (which isn't much to go by to be fair) tells me this is awfully similar to https://github.com/electron/electron/issues/20737 which was fixed in https://github.com/electron/electron/pull/21169 and backported to Electron 6.1.5.

We're currently aiming to [upgrade the version of Electron we're using](https://github.com/desktop/desktop/pull/8791) to 6.1.6 which hopefully resolves this issue. I'm gonna tentatively put this issue in the 2.3 project board and as soon as we ship a beta with Electron 6 we can see if this is still happening.

**Comment by thinkyhead** [comment]
I think this is probably due to an underlying Electron bug, because I quickly get crashes (macOS) when using the context menu to open a file in Sublime. But I've also gotten sudden crashes from doing other innocuous operations in the commit list.

**Comment by dacarver** [comment]
Just confirming this is still happening in version `2.3.1` (which is to be expected, since it's likely an Electron bug).

**Comment by tierninho** [comment]
Update: I was able to reproduce this bug in the current production version of Desktop `v2.3.1` but not in our upcoming beta version `v 2.3.2-beta2`. This release contains the Electron fix [mentioned here](https://github.com/desktop/desktop/issues/8846#issuecomment-571609589).  Although this bug is not reproducible every time you right-click a menu item on a file in the Changes tab, it has so far not been experienced in the new beta build. We hope this is a permanent fix.
