### ISSUE TITLE
Broken Commit Text Windows

### ISSUE THREAD

**Issue by danielghirasim** [desktop/desktop#8915]
### Describe the bug

The format of the commit windows is bugged.

### Version & OS

Github Desktop Version - 2.2.4
Windows 10 - 64 bit

### Steps to reproduce the behavior

Can't reproduce it , it randomly appears

### Expected behavior

The windows Summary (required) + Description box should be properly formatted

### Actual behavior

The format is messed up the summary windows is very narrow

### Screenshots

Tried some messing around with stuff and it fixed itself.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

This helped me fix the issue:

1.Adding Avatar
2.Chaning Back and Forth from Dark/Light Theme
3.Signing out (I think this did it)

**Comment by tierninho** [comment]
@danielghirasim I believe you saw something like this https://github.com/desktop/desktop/issues/5671?

Please confirm and any change you could share your logs? See the Help menu in Desktop. 

Glad you got it fixed with:

> 1. Adding Avatar
> 2. Changing Back and Forth from Dark/Light Theme
> 3. Signing out (I think this did it)

**Comment by danielghirasim** [comment]
> @danielghirasim I believe you saw something like this #5671?
> 
> Please confirm and any chance you could share your logs? See the Help menu in Desktop.
> 
> Glad you got it fixed with:
> 
> > 1. Adding Avatar
> > 2. Changing Back and Forth from Dark/Light Theme
> > 3. Signing out (I think this did it)

Hello,

No, it looked quite different in the sense that the summary input box was much smaller and text was overlapping, I'll share the logs as soon as I get home and maybe try to recreate to bug.

**Comment by danielghirasim** [comment]
Hello,

Here are the log files as promised (I'll attach the last 7 days of logs since the problem persisted)
. I didn't really have time to try to recreate the bug. If it occurs again I'll provide a screenshot and the apropriate log.

[2020-01-10.desktop.production.log](https://github.com/desktop/desktop/files/4067968/2020-01-10.desktop.production.log)
[2020-01-11.desktop.production.log](https://github.com/desktop/desktop/files/4067969/2020-01-11.desktop.production.log)
[2020-01-12.desktop.production.log](https://github.com/desktop/desktop/files/4067970/2020-01-12.desktop.production.log)
[2020-01-13.desktop.production.log](https://github.com/desktop/desktop/files/4067971/2020-01-13.desktop.production.log)
[2020-01-14.desktop.production.log](https://github.com/desktop/desktop/files/4067972/2020-01-14.desktop.production.log)
[2020-01-15.desktop.production.log](https://github.com/desktop/desktop/files/4067973/2020-01-15.desktop.production.log)

**Comment by tierninho** [comment]
Thanks for sending over the logs.

I do see some fetching errors, among others, which could have resulted in Desktop updating with the right data.

```
2020-01-15T21:01:14.205Z - warn: [ui] deserialize: invalid JSON found at 'https://api.github.com/repos/a3m4/YouTube-Report' - status: 200, length: '(missing)' id: '(missing)'
TypeError: Failed to fetch
```

```
2020-01-15T21:01:14.206Z - warn: [ui] fetchRepository: an error occurred for 'a3m4/YouTube-Report'
TypeError: Failed to fetch
```

@desktop/core Anything relevant here?

**Comment by niik** [comment]
Hey, we've been unable to reproduce this and the logs didn't provide us with much to go on either. If this keeps happening please let us know and we can see about reopening, thanks!
