### ISSUE TITLE
The Repository/View On Github button is gray.

### ISSUE THREAD

**Issue by kite8** [desktop/desktop#9040]
### Describe the bug

Recently(I can't remember when this phenomenon started), when I have cloned a repository from someone, the repository belongs to other, but it should belongs to someone, not others, the other repositories don't view on github.

### Version & OS
- Github Desktop: 2.3.1
- OS: Windows 10

### Steps to reproduce the behavior

1. Clone a repository

### Expected behavior

After cloning, can correctly classify, and can view on github.

### Actual behavior

The button of "View On Github" is gray

### Screenshots
The repository [QACTPBeeBroker](https://github.com/yutiansut/QACTPBeeBroker) should belong yutiansut, so I don't how to deal with it.

![bug00](https://user-images.githubusercontent.com/3972363/73711264-4720ce00-4741-11ea-8a73-336e5fb0fa58.png)
![bug01](https://user-images.githubusercontent.com/3972363/73711266-47b96480-4741-11ea-8abd-c48fc8f80722.png)

**Comment by steveward** [comment]
Thanks for the report @kite8. Have you tried removing the repository from GitHub Desktop and then adding the repository back to see if that fixes this issue? You can also clear out the cached data that GitHub Desktop stores, but you will need to add your local repositories back to the application and log in again after doing this. Here's how to do that:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop and log in/add your repositories 

That should resolve this issue -- let me know if it does not.

**Comment by tierninho** [comment]
For future reference, we have identified a less destructive fix. 

Clearing the cache on your folder by: removing all contents of the `%appadata%/github/desktop client/cache` folder should resolve this.

**Comment by jwargo** [comment]
When I encountered this problem, I simply whacked the `%APPDATA%/Github Desktop/Cache` folder contents and that fixed it for me (and didn't make me lose all my repos config).

**Comment by ascendedguard** [comment]
Adding a comment here since this was the first Google result for the issue. I had 403 errors in the console, and wiping the Cache folder did not resolve the issue.

What resolved it for me was to sign out and sign back in, re-authorizing the application for my organizations. After switching to another repo and switching back, View on GitHub button then worked correctly.

**Comment by halter73** [comment]
Thanks for the tip @ascendedguard. In my case, I somehow got logged out of GitHub Desktop, but that wasn't obvious until I looked at `File > Options > Accounts`. Repositories I had added before silently getting signed out appeared to work fully, but newly added local repositories had "View on GitHub" grayed out. Going to `File > Options > Accounts` and signing in again fixed it. I didn't even have to re-add any repositories.
