### ISSUE TITLE
Commit Failed - exit code 128: fatal: .git/index: unable to map index file: invaild argument

### ISSUE THREAD

**Issue by windowsboy111** [desktop/desktop#9153]
When I'm trying to commit after a bunch of editing on my new repository I've got an error:
Commit failed - exit code 128 received, with output: 'fatal: .git/index: unable to map index file: invalid argument'

(Which might be because of my fault because this is the first time I'm using this software.)

OS: Windows 10 Home
Text editor: VS code
The repository on the internet is totally blank besides the readme.md file with 2 lines in it.
and My PC have 2 files with a bunch of "paragraph" in it. readme.md and parkour.txt
So it is totally not committed.

**Comment by tierninho** [comment]
@windowsboy111 Could you attach the full log files? Open Desktop, go to the Help menu, and select the Show Logs menu item. Thanks.

**Comment by windowsboy111** [comment]
[2020-02-21.desktop.production.log](https://github.com/desktop/desktop/files/4237400/2020-02-21.desktop.production.log)

**Comment by tierninho** [comment]
Looks like the path where you cloned the repo is not valid. Try cloning into another directory, perhaps in the C drive?

`fatal: could not create leading directories of 'G:\GitHub\lopixel': No such file or directory`

**Comment by windowsboy111** [comment]
no it isn't, I just typed the wrong path for it a the beginning of clonning it to my device. I've changed that, and I can see files in the right directory. (G:\My Drive\Github\lopixel)
![image](https://user-images.githubusercontent.com/48051237/75079873-4bbcf300-5545-11ea-899b-11f58b77ff17.png)

**Comment by tierninho** [comment]
Thanks for confirming. I take it it is fixed now, so closing the issue.

**Comment by windowsboy111** [comment]
no my problem is not fixed and it is still out of sync!!! :(

**Comment by tierninho** [comment]
Reopening. I misunderstood. What is the status in Desktop?

**Comment by windowsboy111** [comment]
Well I did it before I encounted this problem.

**Comment by windowsboy111** [comment]
Just note that even I typed the summary and description, it still doesn't work. Thanks for trying to help me.

**Comment by tierninho** [comment]
Can you send fresh logs? Thanks!

**Comment by tierninho** [comment]
@windowsboy111  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
