### ISSUE TITLE
2.3.2 beta 4 changed my git name to my github username

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#9255]
### Describe the bug

Upgrading from 2.3.2-beta3 to 2.3.2-beta4 changed my name from `Brian Surowiec` to `xt0rted`. I noticed this after updating and rebasing, now all the changed commits say `Brian surowiec authored and xt0rted committed`.

### Version & OS

- 2.3.2-beta4
- Windows 10

### Steps to reproduce the behavior

1. Start with a version prior to 2.3.2-beta4
2. Under Git Options set your name
3. Update to 2.3.2-beta4
4. Look under Git Options and your name should be different

### Expected behavior

Leave my name as-is

### Actual behavior

Changed my name to my GitHub username without any warning or notice

### Logs

Nothing in the log or devtools mentions this setting change

**Comment by xt0rted** [comment]
Forgot to mention that right after updating I changed my shell from PowerShell to Windows Terminal and rebased from there.

**Comment by niik** [comment]
Hi @xt0rted, thanks for reporting this! We really appreciate reports from beta users.

I haven't been able to reproduce the problem but I have a hunch of what could have happened. Are you able to consistently reproduce it on your machine?

My hunch is this. When the preferences dialog is opened we attempt to retrieve the config value for the key `user.name` by executing `git config --global user.name` through the [getGlobalConfigValue](https://github.com/desktop/desktop/blob/681f11a34d304cce4cce9edb9a133e412488443f/app/src/lib/git/config.ts#L14) method.

If `git config` can't find the key its looking for it'll exit with the exit code `1` which we then treat as a "key not found error"

https://github.com/desktop/desktop/blob/681f11a34d304cce4cce9edb9a133e412488443f/app/src/lib/git/config.ts#L88-L96

Unfortunately though there are more cases than just the key not being found that can cause Git to exit with an exit code of 1. Being unable to read the config file is one of them

```
MacBook-Pro:~ markus$ chmod 000 .gitconfig 
MacBook-Pro:~ markus$ git config --global user.name ; echo $?
warning: unable to access '/Users/markus/.gitconfig': Permission denied
warning: unable to access '/Users/markus/.gitconfig': Permission denied
1
```

So what I think happened here is for some reason the `git config` invocation GitHub Desktop ran to get your `user.name` config value when opening the preferences dialog failed and we then treated that as the key not existing and subsequently prefilled it with a sane default

https://github.com/desktop/desktop/blob/681f11a34d304cce4cce9edb9a133e412488443f/app/src/ui/preferences/preferences.tsx#L127-L133

If my hunch is correct then this isn't a new problem in the latest beta so it would be really helpful tot know if you're able to consistently reproduce this by changing some random setting in the preferences dialog and saving.

**Comment by xt0rted** [comment]
@niik I have a repro now.

I keep my `.gitigore` at [xt0rted/dotfiles](https://github.com/xt0rted/dotfiles/blob/master/.gitconfig) so I can share it between my machines, and in doing so I've moved the `user.name` and `user.email` values out to an `overrides.gitconfig` that gets included at the end.

GitHub Desktop no longer sees my name or email with this setup and ends up setting its own values. These are only written to my `.gitconfig` when I save my settings, even something unrelated such as changing my shell.

If I delete the newly added values and re-open GitHub Desktop my name and email are set back to my account values and the process repeats.

You're probably right that this isn't a beta 4 issue, but since I changed my settings after the update that's why the values ended up getting reset in my config.

**Comment by niik** [comment]
@xt0rted Thanks so much for troubleshooting and getting back to us so quickly! While not ideal I believe this behavior has existed for a very long time. The overall implementation of falling back to the account login/name was introduced 3 years ago in https://github.com/desktop/desktop/commit/9aff0e6d655c3a8955e0dbda661143441d6e1cd4.

Given that this is a long-standing issue and given that I suspect that the use of config include directives are extremely rare among our users I don't think this is something we should attempt to address for the next release.

Allow myself to solutionize for just a second however I'd say that while we could attempt to respect include directives either using the `--include` flag or by means of relying on `--list` plus `--show-origin` I fear such attempts will be brittle at best due to the complexity involved and I think a better approach would be to remove the automatic pre-fill from the preferences dialog while still keeping it in the welcome flow. Those are my initial thoughts that I thought worth capturing for future reference.

**Comment by billygriffin** [comment]
> I think a better approach would be to remove the automatic pre-fill from the preferences dialog while still keeping it in the welcome flow. Those are my initial thoughts that I thought worth capturing for future reference.

I agree with this suggestion from @niik - I'm curious your thoughts @ampinsk. Basically the welcome flow would still prefill the Git info with your username and email from GitHub, but after that the preferences dialog doesn't do anything special with those fields other than showing them and allowing you to change them manually if you so choose.

**Comment by ampinsk** [comment]
👍 Makes sense, agree with this approach!

**Comment by say25** [comment]
I think this has recently be addressed and fixed with the linked PR above and some other recent work.

**Comment by xt0rted** [comment]
@say25 the original issue still exists in 2.6.4-beta2. My name shows as `xt0rted` in the settings dialog even though it's set to `Brian Surowiec` in my config include. I'm not sure what happened recently but something caused these settings to be saved to my `.gitconfig` again and messed up a week or more worth of commits on me. For now I've stopped using the include because it's not worth the headache this keeps causing me.

**Comment by steveward** [comment]
@xt0rted I'm going to consolidate this into https://github.com/desktop/desktop/issues/12041 where we are tracking issues around conditional includes.
